/* Generated by gimple_codegen.py (Milestone B: C++20-coroutine
   translation of this module's supported generator function(s);
   Milestone C step 2 added `yield from`-delegation support;
   Milestone C step 3 added generator METHODS on structs;
   Milestone D added try/except/raise support;
   Step B (async/await project) added compiled `async def`
   functions -- a separate promise_type/extern "C" API from the
   generator one above, deliberately not sharing a promise shape
   -- see GimpleGen._gen_cpp_async_unit's docstring) */
#include <coroutine>
#include <cstdint>
#include <cstdio>
#include <cmath>
#include <exception>
#include <functional>
#include <vector>
#include <algorithm>
#include <fire_runtime.h>

extern "C" { typedef struct MojoGenerator MojoGenerator; }
extern "C" { typedef struct MojoAsync MojoAsync; }

/* Milestone D: RAII `finally:` translation (see
   GimpleGen._cpp_try_stmt) -- runs an arbitrary capturing
   lambda from its destructor, so it fires on every way its
   enclosing scope can be exited (normal fallthrough, break/
   continue, co_return, an exception unwinding through/past it,
   or -- same C++20 coroutine-frame-destruction rule as
   `_mojogen_sub_guard` below -- this coroutine being destroyed
   early while suspended inside the guarded scope). A capturing
   lambda (not a local class) specifically: a local class's own
   member functions have NO implicit access to the enclosing
   function's locals, so a finally body referencing an outer
   variable wouldn't compile with that approach. */
struct _MojoScopeExit {
    std::function<void()> fn;
    explicit _MojoScopeExit(std::function<void()> f) : fn(std::move(f)) {}
    ~_MojoScopeExit() { fn(); }
};

/* Milestone D: a Mojo exception thrown as a real C++ exception,
   confined to this coroutine's own .cpp translation unit (see
   GimpleGen._cpp_raise_stmt/_cpp_try_stmt). Carries exactly the
   same tri-part representation the ordinary (non-generator) GIMPLE
   path already uses for its mojo_exc_type/msg/obj globals (see
   fire_runtime.h) -- reused, not reinvented, so the extern "C"
   `_resume` boundary below can translate one directly into the
   other with no lossy conversion. */
struct _MojoCppExc {
    int64_t type_id;
    char *msg;
    void *obj;
};

/* RAII guard for a sub-generator a `yield from` delegates to (see
   GimpleGen._cpp_yield_from) -- guarantees the sub-generator's own
   `_destroy` runs exactly once, whether this scope exits because the
   sub-generator was exhausted normally or because the OUTER coroutine
   holding it is itself destroyed early (e.g. a consumer `break`s out
   of the loop that's driving it): C++20 destroys every local object
   in scope at a coroutine's suspension point when that coroutine's
   frame is destroyed, exactly as if the enclosing block unwound
   normally, so this destructor fires correctly in both cases with no
   special-case code at either call site. Emitted unconditionally
   whenever this module has ANY compiled generator -- harmless and
   unused if none of them actually use `yield from`. */
struct _mojogen_sub_guard {
    MojoGenerator *g;
    void (*destroy_fn)(MojoGenerator *);
    ~_mojogen_sub_guard() { if (g) destroy_fn(g); }
};

struct _mojogen_dump_promise;
using _mojogen_dump_handle = std::coroutine_handle<_mojogen_dump_promise>;
struct _mojogen_dump_Task {
    using promise_type = _mojogen_dump_promise;
    _mojogen_dump_handle h;
};
struct _mojogen_dump_promise {
    int64_t current_value{};
    _mojogen_dump_Task get_return_object() { return _mojogen_dump_Task{ _mojogen_dump_handle::from_promise(*this) }; }
    std::suspend_always initial_suspend() noexcept { return {}; }
    std::suspend_always final_suspend() noexcept { return {}; }
    void unhandled_exception() {
        try { std::rethrow_exception(std::current_exception()); }
        catch (_MojoCppExc &__e) {
            mojo_exc_type_set(__e.type_id);
            mojo_exc_msg_set(__e.msg);
            mojo_exc_obj_set(__e.obj);
            mojo_exc_pending_set(1);
        }
        catch (...) {
            /* Some other, non-Mojo C++ exception (e.g. a
               std::bad_alloc) escaped -- tag 0 (untyped) so
               it's still reported/catchable as SOME pending
               exception rather than silently discarded. */
            mojo_exc_type_set(0);
            mojo_exc_msg_set(nullptr);
            mojo_exc_obj_set(nullptr);
            mojo_exc_pending_set(1);
        }
    }
    std::suspend_always yield_value(int64_t v) { current_value = v; return {}; }
    void return_void() {}
};
static _mojogen_dump_Task _mojogen_dump_impl (int64_t d, int64_t prefix) {
    MojoList * items;
    items = (MojoList *)(mojo_sorted((void *)(d)));
    int64_t item;
    for (int64_t _mg_i_1 = 0; _mg_i_1 < mojo_list_len((MojoList *)(items)); _mg_i_1++) {
        item = mojo_list_get_int((MojoList *)(items), _mg_i_1);
        co_yield mojo_str_cat((char *)(mojo_str_cat((char *)(mojo_str_cat((char *)(mojo_str_cat((char *)(mojo_str_cat((char *)(mojo_str_cat((char *)("#define "), (char *)(mojo_str((void *)(prefix))))), (char *)("_"))), (char *)(mojo_str((void *)(item))))), (char *)(" "))), (char *)(mojo_str((void *)(item))))), (char *)("\n"));
    }
    co_return;
}
extern "C" MojoGenerator *_mojogen_dump_start (int64_t d, int64_t prefix) {
    _mojogen_dump_Task t = _mojogen_dump_impl (d, prefix);
    return reinterpret_cast<MojoGenerator *>(t.h.address());
}
extern "C" bool _mojogen_dump_resume (MojoGenerator *g) {
    _mojogen_dump_handle h = _mojogen_dump_handle::from_address(reinterpret_cast<void *>(g));
    if (h.done()) return false;
    mojo_exc_pending_set(0);
    h.resume();
    if (mojo_exc_pending_get()) return false;
    return !h.done();
}
extern "C" int64_t _mojogen_dump_value (MojoGenerator *g) {
    _mojogen_dump_handle h = _mojogen_dump_handle::from_address(reinterpret_cast<void *>(g));
    return h.promise().current_value;
}
extern "C" void _mojogen_dump_destroy (MojoGenerator *g) {
    _mojogen_dump_handle h = _mojogen_dump_handle::from_address(reinterpret_cast<void *>(g));
    if (h) h.destroy();
}

struct _mojogen_dump2_promise;
using _mojogen_dump2_handle = std::coroutine_handle<_mojogen_dump2_promise>;
struct _mojogen_dump2_Task {
    using promise_type = _mojogen_dump2_promise;
    _mojogen_dump2_handle h;
};
struct _mojogen_dump2_promise {
    int64_t current_value{};
    _mojogen_dump2_Task get_return_object() { return _mojogen_dump2_Task{ _mojogen_dump2_handle::from_promise(*this) }; }
    std::suspend_always initial_suspend() noexcept { return {}; }
    std::suspend_always final_suspend() noexcept { return {}; }
    void unhandled_exception() {
        try { std::rethrow_exception(std::current_exception()); }
        catch (_MojoCppExc &__e) {
            mojo_exc_type_set(__e.type_id);
            mojo_exc_msg_set(__e.msg);
            mojo_exc_obj_set(__e.obj);
            mojo_exc_pending_set(1);
        }
        catch (...) {
            /* Some other, non-Mojo C++ exception (e.g. a
               std::bad_alloc) escaped -- tag 0 (untyped) so
               it's still reported/catchable as SOME pending
               exception rather than silently discarded. */
            mojo_exc_type_set(0);
            mojo_exc_msg_set(nullptr);
            mojo_exc_obj_set(nullptr);
            mojo_exc_pending_set(1);
        }
    }
    std::suspend_always yield_value(int64_t v) { current_value = v; return {}; }
    void return_void() {}
};
static _mojogen_dump2_Task _mojogen_dump2_impl (int64_t d, int64_t prefix) {
    MojoList * items;
    items = [&]() -> MojoList * { MojoList * _mg_acc_3 = mojo_list_new (); int64_t _mg_it_2 = 0; return _mg_acc_3; }();
    MojoList *_mg_sorted_4 = (MojoList *)((MojoList *)(mojo_sorted((void *)(items))));
    int64_t value;
    int64_t name;
    for (int64_t _mg_i_5 = 0; _mg_i_5 < mojo_list_len((MojoList *)(_mg_sorted_4)); _mg_i_5++) {
        MojoList *_mg_tup_6 = (MojoList *)(mojo_list_get_int((MojoList *)(_mg_sorted_4), _mg_i_5));
        value = mojo_list_get_int(_mg_tup_6, 0);
        name = mojo_list_get_int(_mg_tup_6, 1);
        co_yield mojo_str_cat((char *)(mojo_str_cat((char *)(mojo_str_cat((char *)(mojo_str_cat((char *)("#define "), (char *)(mojo_str((void *)(name))))), (char *)(" "))), (char *)(mojo_str((void *)(value))))), (char *)("\n"));
    }
    co_return;
}
extern "C" MojoGenerator *_mojogen_dump2_start (int64_t d, int64_t prefix) {
    _mojogen_dump2_Task t = _mojogen_dump2_impl (d, prefix);
    return reinterpret_cast<MojoGenerator *>(t.h.address());
}
extern "C" bool _mojogen_dump2_resume (MojoGenerator *g) {
    _mojogen_dump2_handle h = _mojogen_dump2_handle::from_address(reinterpret_cast<void *>(g));
    if (h.done()) return false;
    mojo_exc_pending_set(0);
    h.resume();
    if (mojo_exc_pending_get()) return false;
    return !h.done();
}
extern "C" int64_t _mojogen_dump2_value (MojoGenerator *g) {
    _mojogen_dump2_handle h = _mojogen_dump2_handle::from_address(reinterpret_cast<void *>(g));
    return h.promise().current_value;
}
extern "C" void _mojogen_dump2_destroy (MojoGenerator *g) {
    _mojogen_dump2_handle h = _mojogen_dump2_handle::from_address(reinterpret_cast<void *>(g));
    if (h) h.destroy();
}

struct _mojogen_dump_gotos_promise;
using _mojogen_dump_gotos_handle = std::coroutine_handle<_mojogen_dump_gotos_promise>;
struct _mojogen_dump_gotos_Task {
    using promise_type = _mojogen_dump_gotos_promise;
    _mojogen_dump_gotos_handle h;
};
struct _mojogen_dump_gotos_promise {
    char * current_value{};
    _mojogen_dump_gotos_Task get_return_object() { return _mojogen_dump_gotos_Task{ _mojogen_dump_gotos_handle::from_promise(*this) }; }
    std::suspend_always initial_suspend() noexcept { return {}; }
    std::suspend_always final_suspend() noexcept { return {}; }
    void unhandled_exception() {
        try { std::rethrow_exception(std::current_exception()); }
        catch (_MojoCppExc &__e) {
            mojo_exc_type_set(__e.type_id);
            mojo_exc_msg_set(__e.msg);
            mojo_exc_obj_set(__e.obj);
            mojo_exc_pending_set(1);
        }
        catch (...) {
            /* Some other, non-Mojo C++ exception (e.g. a
               std::bad_alloc) escaped -- tag 0 (untyped) so
               it's still reported/catchable as SOME pending
               exception rather than silently discarded. */
            mojo_exc_type_set(0);
            mojo_exc_msg_set(nullptr);
            mojo_exc_obj_set(nullptr);
            mojo_exc_pending_set(1);
        }
    }
    std::suspend_always yield_value(char * v) { current_value = v; return {}; }
    void return_void() {}
};
static _mojogen_dump_gotos_Task _mojogen_dump_gotos_impl (int64_t d, int64_t prefix) {
    int64_t i;
    int64_t item;
    for (int64_t _mg_i_7 = 0; _mg_i_7 < mojo_list_len((MojoList *)((MojoList *)(mojo_sorted((void *)(d))))); _mg_i_7++) {
        i = _mg_i_7;
        item = mojo_list_get_int((MojoList *)((MojoList *)(mojo_sorted((void *)(d)))), _mg_i_7);
        co_yield mojo_str_cat((char *)(mojo_str_cat((char *)(mojo_str_cat((char *)(mojo_str_cat((char *)("    &&"), (char *)(mojo_str((void *)(prefix))))), (char *)("_"))), (char *)(mojo_str((void *)(item))))), (char *)(",\n"));
    }
    co_return;
}
extern "C" MojoGenerator *_mojogen_dump_gotos_start (int64_t d, int64_t prefix) {
    _mojogen_dump_gotos_Task t = _mojogen_dump_gotos_impl (d, prefix);
    return reinterpret_cast<MojoGenerator *>(t.h.address());
}
extern "C" bool _mojogen_dump_gotos_resume (MojoGenerator *g) {
    _mojogen_dump_gotos_handle h = _mojogen_dump_gotos_handle::from_address(reinterpret_cast<void *>(g));
    if (h.done()) return false;
    mojo_exc_pending_set(0);
    h.resume();
    if (mojo_exc_pending_get()) return false;
    return !h.done();
}
extern "C" char * _mojogen_dump_gotos_value (MojoGenerator *g) {
    _mojogen_dump_gotos_handle h = _mojogen_dump_gotos_handle::from_address(reinterpret_cast<void *>(g));
    return h.promise().current_value;
}
extern "C" void _mojogen_dump_gotos_destroy (MojoGenerator *g) {
    _mojogen_dump_gotos_handle h = _mojogen_dump_gotos_handle::from_address(reinterpret_cast<void *>(g));
    if (h) h.destroy();
}
