# AUTO-GENERATED by gimple_spec_gen.py — do not edit directly.
# Regenerate with: python gimple_spec_gen.py --output-module generated_dispatch.py
# Sources: GNU-EXTENSIONS.md, gimple-type-system.md

# ---------------------------------------------------------------------------
# Type lattice rank tables  (source: gimple-type-system.md)
# ---------------------------------------------------------------------------

_SIGNED: dict = {
    'int8_t': 1,
    'int16_t': 2,
    'int32_t': 3,
    'int': 3,
    'int64_t': 4,
}

_UNSIGNED: dict = {
    'uint8_t': 1,
    'uint16_t': 2,
    'uint32_t': 3,
    'unsigned int': 3,
    'uint64_t': 4,
}

_FLOAT: dict = {
    '__fp16': 1,
    'float': 2,
    'double': 3,
}

# ---------------------------------------------------------------------------
# Operator tables  (source: GNU-EXTENSIONS.md)
# ---------------------------------------------------------------------------

# Mojo operator → C infix operator.
# ** // @ are absent; they have dedicated lowering routines.
_BIN_OPS: dict = {
    '+': '+',
    '-': '-',
    '*': '*',
    '/': '/',
    '%': '%',
    '&': '&',
    '|': '|',
    '^': '^',
    '<<': '<<',
    '>>': '>>',
    '==': '==',
    '!=': '!=',
    '<': '<',
    '<=': '<=',
    '>': '>',
    '>=': '>=',
    'and': '&&',
    'or': '||',
    'is': '==',
    'is not': '!=',
}

_CMP_OPS: set = {
    '!=',
    '<',
    '<=',
    '==',
    '>',
    '>=',
    'and',
    'is',
    'is not',
    'or',
}

# ---------------------------------------------------------------------------
# Statement dispatch table
# Maps AST node type.__name__ → method name on GimpleCodegen
# ---------------------------------------------------------------------------

_STMT_DISPATCH: dict = {
    'PassStmt': '_gen_stmt_PassStmt',
    'VarDecl': '_gen_stmt_VarDecl',
    'AssignStmt': '_gen_stmt_AssignStmt',
    'AugAssignStmt': '_gen_stmt_AugAssignStmt',
    'MultiAssignStmt': '_gen_stmt_MultiAssignStmt',
    'ReturnStmt': '_gen_stmt_ReturnStmt',
    'IfStmt': '_gen_stmt_IfStmt',
    'WhileStmt': '_gen_stmt_WhileStmt',
    'ForStmt': '_gen_stmt_ForStmt',
    'BreakStmt': '_gen_stmt_BreakStmt',
    'ContinueStmt': '_gen_stmt_ContinueStmt',
    'ExprStmt': '_gen_stmt_ExprStmt',
    'AssertStmt': '_gen_stmt_AssertStmt',
    'RaiseStmt': '_gen_stmt_RaiseStmt',
    'TryStmt': '_gen_stmt_TryStmt',
    'WithStmt': '_gen_stmt_WithStmt',
    'FunctionDef': '_gen_stmt_FunctionDef',
    'ImportStmt': '_gen_stmt_ImportStmt',
    'FromImportStmt': '_gen_stmt_FromImportStmt',
    'ComptimeIfStmt': '_gen_stmt_ComptimeIfStmt',
    'ComptimeForStmt': '_gen_stmt_ComptimeForStmt',
    'ComptimeVarStmt': '_gen_stmt_ComptimeVarStmt',
    'GlobalStmt': '_gen_stmt_GlobalStmt',
    'MatchStmt': '_gen_stmt_MatchStmt',
}

# ---------------------------------------------------------------------------
# Expression dispatch table
# Maps AST node type.__name__ → method name on GimpleCodegen
# ---------------------------------------------------------------------------

_EXPR_DISPATCH: dict = {
    'IntLiteral': '_lower_IntLiteral',
    'FloatLiteral': '_lower_FloatLiteral',
    'BoolLiteral': '_lower_BoolLiteral',
    'EllipsisLiteral': '_lower_EllipsisLiteral',
    'StringLiteral': '_lower_StringLiteral',
    'IdentExpr': '_lower_IdentExpr',
    'WalrusExpr': '_lower_WalrusExpr',
    'BinaryOp': '_lower_binary',
    'UnaryOp': '_lower_UnaryOp',
    'CallExpr': '_lower_call',
    'TernaryExpr': '_lower_TernaryExpr',
    'MemberExpr': '_lower_MemberExpr',
    'SubscriptExpr': '_lower_subscript',
    'SliceExpr': '_lower_slice',
    'ListExpr': '_lower_list_literal',
    'DictExpr': '_lower_dict_literal',
    'SetExpr': '_lower_set_literal',
    'TupleExpr': '_lower_tuple_literal',
    'Comprehension': '_lower_comprehension',
    'LambdaExpr': '_lower_LambdaExpr',
}
