/* Generated by gimple_codegen.py */
/* Compile with: gcc -fgimple -fsyntax-only file.c (uses gcc-15 if available) */
#include <stdint.h>
#include <stdlib.h>
#include <math.h>
#include <stdio.h>
#include <setjmp.h>
#include "mojo_runtime.h"

static int __mojo_floordiv (int a, int b)
{
  int q = a / b;
  return q - (a % b != 0 && (a ^ b) < 0);
}

static int * _mojo_at_int (int * p, int64_t n) { return p + n; }

char * format_ast (int, int);
int main (void);

/* TODO: top-level ExprStmt */
char * __GIMPLE format_ast (int node, int indent)
{
  char * _t1;
  char * _t2;
  char * prefix;
  _Bool _t3;
  char * _t4;
  int _t5;
  int _t6;
  char * _t7;
  char * _t8;
  MojoList * _t9;
  int64_t _t10;
  int64_t _t11;
  int _t12;
  int _t13;
  char * _t14;
  char * _t15;
  int _t16;
  int _t17;
  char * _t18;
  char * _t19;
  int _t20;
  _Bool _t21;
  char * _t22;
  MojoList * _t23;
  char * _t24;
  MojoList * lines;
  char * _t25;
  int _t26;
  int _t27;
  char * _t28;
  int _t29;
  int _t30;
  int node_type;
  MojoList * _t31;
  char * _t32;
  char * _t33;
  char * _t34;
  int _t35;
  int _t36;
  int _t37;
  char * _t38;
  int _t39;
  int _t40;
  char * _t41;

bb_2:
  _t1 = (char *)indent;
  _t2 = "\"  \"" * _t1;
  prefix = _t2;
  _t3 = node == None;
  if (_t3) goto bb_3; else goto bb_4;

bb_3:
  _t4 = prefix + "\"None\"";
  return _t4;
  goto bb_4;

bb_4:
  _t5 = isinstance (node, bool);
  if (_t5) goto bb_5; else goto bb_6;

bb_5:
  _t6 = str (node);
  _t7 = (char *)_t6;
  _t8 = prefix + _t7;
  return _t8;
  goto bb_6;

bb_6:
  _t9 = mojo_list_new ();
  _t10 = (int64_t)int;
  mojo_list_append_int (_t9, _t10);
  _t11 = (int64_t)float;
  mojo_list_append_int (_t9, _t11);
  _t12 = isinstance (node, _t9);
  if (_t12) goto bb_7; else goto bb_8;

bb_7:
  _t13 = str (node);
  _t14 = (char *)_t13;
  _t15 = prefix + _t14;
  return _t15;
  goto bb_8;

bb_8:
  _t16 = isinstance (node, str);
  if (_t16) goto bb_9; else goto bb_10;

bb_9:
  _t17 = repr (node);
  _t18 = (char *)_t17;
  _t19 = prefix + _t18;
  return _t19;
  goto bb_10;

bb_10:
  _t20 = isinstance (node, list);
  if (_t20) goto bb_11; else goto bb_12;

bb_11:
  _t21 = node == 0;
  if (_t21) goto bb_13; else goto bb_14;

bb_13:
  _t22 = prefix + "\"[]\"";
  return _t22;
  goto bb_14;

bb_14:
  _t23 = mojo_list_new ();
  _t24 = prefix + "\"[\"";
  mojo_list_append_str (_t23, _t24);
  lines = _t23;
  /* TODO: for loop over int */
  _t25 = prefix + "\"]\"";
  _t26 = MojoList_append (lines, _t25);
  _t27 = char_join ("\"\\n\"", lines);
  _t28 = (char *)_t27;
  return _t28;
  goto bb_12;

bb_12:
  _t29 = type (node);
  _t30 = _t29.__name__;
  node_type = _t30;
  _t31 = mojo_list_new ();
  _t32 = (char *)node_type;
  _t33 = prefix + _t32;
  _t34 = _t33 + "\"(\"";
  mojo_list_append_str (_t31, _t34);
  lines = _t31;
  _t35 = hasattr (node, "\"__dict__\"");
  if (_t35) goto bb_15; else goto bb_16;

bb_15:
  _t36 = node.__dict__;
  _t37 = int_items (_t36);
  /* TODO: for loop over int */
  goto bb_16;

bb_16:
  _t38 = prefix + "\")\"";
  _t39 = MojoList_append (lines, _t38);
  _t40 = char_join ("\"\\n\"", lines);
  _t41 = (char *)_t40;
  return _t41;
}

int __GIMPLE main (void)
{
  int _t1;
  int _t2;
  int _t3;
  _Bool _t4;
  int _t5;
  int64_t _t6;
  int _t7;
  int _t8;
  int path;
  int _t9;
  _Bool _t10;
  int _t11;
  int f;
  int _t12;
  int src;
  int _t13;
  _Bool _t14;
  int _t15;
  int ast;
  char * _t16;
  char * e;
  int _t17;
  char * _t18;
  char * _t19;
  char * _t20;
  int _t21;
  int tokens;

bb_2:
  _t1 = sys.argv;
  _t2 = sys.argv;
  _t3 = len (_t2);
  _t4 = _t3 != 2;
  if (_t4) goto bb_3; else goto bb_4;

bb_3:
  return;
  goto bb_4;

bb_4:
  _t5 = sys.argv;
  _t6 = (int64_t) 1;
  _t7 = _mojo_at_int (_t5, _t6);
  _t8 = *_t7;
  path = _t8;
  _t9 = mojo_try_push ();
  _t10 = _t9 != 0;
  if (_t10) goto bb_6; else goto bb_5;

bb_5:
  _t11 = open (path);
  f = _t11;
  /* with: __enter__ (int) */
  _t12 = int_read (f);
  src = _t12;
  /* with: __exit__ (int) */
  mojo_exc_pop ();
  goto bb_7;

bb_6:
  mojo_exc_pop ();
  return;
  goto bb_7;

bb_7:
  _t13 = mojo_try_push ();
  _t14 = _t13 != 0;
  if (_t14) goto bb_9; else goto bb_8;

bb_8:
  _t15 = parse (src);
  ast = _t15;
  _t16 = format_ast (ast);
  printf ("%s\n", _t16);
  mojo_exc_pop ();
  goto bb_10;

bb_9:
  mojo_exc_pop ();
  e = (char *) mojo_exc_msg_get ();
  _t17 = str (e);
  _t18 = (char *)_t17;
  _t19 = "\"/* parse error: \"" + _t18;
  _t20 = _t19 + "\" */\"";
  printf ("%s\n", _t20);
  _t21 = py_tokenize (src);
  tokens = _t21;
  /* TODO: for loop over int */
  goto bb_10;

bb_10:
  return 0;
}
