/* Generated by gimple_codegen.py (Milestone B: C++20-coroutine
   translation of this module's supported generator function(s);
   Milestone C step 2 added `yield from`-delegation support;
   Milestone C step 3 added generator METHODS on structs;
   Milestone D added try/except/raise support;
   Step B (async/await project) added compiled `async def`
   functions -- a separate promise_type/extern "C" API from the
   generator one above, deliberately not sharing a promise shape
   -- see GimpleGen._gen_cpp_async_unit's docstring) */
#include <coroutine>
#include <cstdint>
#include <cstdio>
#include <cmath>
#include <exception>
#include <functional>
#include <vector>
#include <algorithm>
#include <fire_runtime.h>

extern "C" { typedef struct MojoGenerator MojoGenerator; }
extern "C" { typedef struct MojoAsync MojoAsync; }

/* Milestone D: RAII `finally:` translation (see
   GimpleGen._cpp_try_stmt) -- runs an arbitrary capturing
   lambda from its destructor, so it fires on every way its
   enclosing scope can be exited (normal fallthrough, break/
   continue, co_return, an exception unwinding through/past it,
   or -- same C++20 coroutine-frame-destruction rule as
   `_mojogen_sub_guard` below -- this coroutine being destroyed
   early while suspended inside the guarded scope). A capturing
   lambda (not a local class) specifically: a local class's own
   member functions have NO implicit access to the enclosing
   function's locals, so a finally body referencing an outer
   variable wouldn't compile with that approach. */
struct _MojoScopeExit {
    std::function<void()> fn;
    explicit _MojoScopeExit(std::function<void()> f) : fn(std::move(f)) {}
    ~_MojoScopeExit() { fn(); }
};

/* Milestone D: a Mojo exception thrown as a real C++ exception,
   confined to this coroutine's own .cpp translation unit (see
   GimpleGen._cpp_raise_stmt/_cpp_try_stmt). Carries exactly the
   same tri-part representation the ordinary (non-generator) GIMPLE
   path already uses for its mojo_exc_type/msg/obj globals (see
   fire_runtime.h) -- reused, not reinvented, so the extern "C"
   `_resume` boundary below can translate one directly into the
   other with no lossy conversion. */
struct _MojoCppExc {
    int64_t type_id;
    char *msg;
    void *obj;
};

/* RAII guard for a sub-generator a `yield from` delegates to (see
   GimpleGen._cpp_yield_from) -- guarantees the sub-generator's own
   `_destroy` runs exactly once, whether this scope exits because the
   sub-generator was exhausted normally or because the OUTER coroutine
   holding it is itself destroyed early (e.g. a consumer `break`s out
   of the loop that's driving it): C++20 destroys every local object
   in scope at a coroutine's suspension point when that coroutine's
   frame is destroyed, exactly as if the enclosing block unwound
   normally, so this destructor fires correctly in both cases with no
   special-case code at either call site. Emitted unconditionally
   whenever this module has ANY compiled generator -- harmless and
   unused if none of them actually use `yield from`. */
struct _mojogen_sub_guard {
    MojoGenerator *g;
    void (*destroy_fn)(MojoGenerator *);
    ~_mojogen_sub_guard() { if (g) destroy_fn(g); }
};

/* Extern declarations for module-level symbols
   referenced by this module's compiled generator
   bodies (compiled standalone, linked with the .ci). */
extern "C" int64_t update_file_with_tmpfile_bb756f (char *, char *, int);

struct _mojogen_updating_file_with_tmpfile_promise;
using _mojogen_updating_file_with_tmpfile_handle = std::coroutine_handle<_mojogen_updating_file_with_tmpfile_promise>;
struct _mojogen_updating_file_with_tmpfile_Task {
    using promise_type = _mojogen_updating_file_with_tmpfile_promise;
    _mojogen_updating_file_with_tmpfile_handle h;
};
struct _mojogen_updating_file_with_tmpfile_promise {
    MojoList * current_value{};
    _mojogen_updating_file_with_tmpfile_Task get_return_object() { return _mojogen_updating_file_with_tmpfile_Task{ _mojogen_updating_file_with_tmpfile_handle::from_promise(*this) }; }
    std::suspend_always initial_suspend() noexcept { return {}; }
    std::suspend_always final_suspend() noexcept { return {}; }
    void unhandled_exception() {
        try { std::rethrow_exception(std::current_exception()); }
        catch (_MojoCppExc &__e) {
            mojo_exc_type_set(__e.type_id);
            mojo_exc_msg_set(__e.msg);
            mojo_exc_obj_set(__e.obj);
            mojo_exc_pending_set(1);
        }
        catch (...) {
            /* Some other, non-Mojo C++ exception (e.g. a
               std::bad_alloc) escaped -- tag 0 (untyped) so
               it's still reported/catchable as SOME pending
               exception rather than silently discarded. */
            mojo_exc_type_set(0);
            mojo_exc_msg_set(nullptr);
            mojo_exc_obj_set(nullptr);
            mojo_exc_pending_set(1);
        }
    }
    std::suspend_always yield_value(MojoList * v) { current_value = v; return {}; }
    void return_void() {}
};
static _mojogen_updating_file_with_tmpfile_Task _mojogen_updating_file_with_tmpfile_impl (char * filename, char * tmpfile) {
    int64_t line;
    char * newline;
    if ((mojo_strlen((char *)(tmpfile)) == 0)) {
        tmpfile = mojo_str_cat((char *)(filename), (char *)(".tmp"));
    }
    else if (int_isdir(0, (int64_t)(char *)(tmpfile))) {
        tmpfile = mojo_path_join((char *)(tmpfile), (char *)(mojo_str_cat((char *)(filename), (char *)(".tmp"))));
    }
    int64_t infile;
    line = 0;
    if (0) {
        newline = "\r\n";
    }
    else if (0) {
        newline = "\r";
    }
    else if (0) {
        newline = "\n";
    }
    else {
        throw _MojoCppExc{ (int64_t)663468903, mojo_str_cat((char *)(mojo_str_cat((char *)(mojo_str_cat((char *)("unknown end of line: "), (char *)(filename))), (char *)(": "))), (char *)(mojo_str((void *)(line)))), (void *)mojo_str_cat((char *)(mojo_str_cat((char *)(mojo_str_cat((char *)("unknown end of line: "), (char *)(filename))), (char *)(": "))), (char *)(mojo_str((void *)(line)))) };
    }
    int64_t outfile;
    MojoList *_mg_tup_1 = mojo_list_new();
    mojo_list_append_int(_mg_tup_1, (int64_t)(infile));
    mojo_list_append_int(_mg_tup_1, (int64_t)(outfile));
    mojo_mark_as_tuple(_mg_tup_1);
    co_yield _mg_tup_1;
    update_file_with_tmpfile_bb756f(filename, tmpfile);
    co_return;
}
extern "C" MojoGenerator *_mojogen_updating_file_with_tmpfile_start (char * filename, char * tmpfile) {
    _mojogen_updating_file_with_tmpfile_Task t = _mojogen_updating_file_with_tmpfile_impl (filename, tmpfile);
    return reinterpret_cast<MojoGenerator *>(t.h.address());
}
extern "C" bool _mojogen_updating_file_with_tmpfile_resume (MojoGenerator *g) {
    _mojogen_updating_file_with_tmpfile_handle h = _mojogen_updating_file_with_tmpfile_handle::from_address(reinterpret_cast<void *>(g));
    if (h.done()) return false;
    mojo_exc_pending_set(0);
    h.resume();
    if (mojo_exc_pending_get()) return false;
    return !h.done();
}
extern "C" MojoList * _mojogen_updating_file_with_tmpfile_value (MojoGenerator *g) {
    _mojogen_updating_file_with_tmpfile_handle h = _mojogen_updating_file_with_tmpfile_handle::from_address(reinterpret_cast<void *>(g));
    return h.promise().current_value;
}
extern "C" void _mojogen_updating_file_with_tmpfile_destroy (MojoGenerator *g) {
    _mojogen_updating_file_with_tmpfile_handle h = _mojogen_updating_file_with_tmpfile_handle::from_address(reinterpret_cast<void *>(g));
    if (h) h.destroy();
}
