/* Generated by gimple_codegen.py */
/* Compile with: gcc -fgimple -fsyntax-only file.c (uses gcc-15 if available) */
#define USE_PYTHON 0
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdio.h>
#include <setjmp.h>
#include <dlfcn.h>
#if USE_PYTHON
#include <Python.h>
#endif
#include <fire_runtime.h>
/* GPU introspection entry points; present in every module so a
   program can ask whether the device path was taken. */
int64_t _mojo_gpu_kernel_count(void);
int64_t _mojo_gpu_have_device(void);
int64_t _mojo_gpu_dispatch_count(void);
int64_t _mojo_gpu_failure_count(void);
#include <fire_sqlite3.h>
#include <fire_zlib.h>
#include <fire_ssl.h>
#include <fire_ncurses.h>
/* Disable security wrappers: sprintf/snprintf/memcpy/memmove/memset/
   strcpy/strncpy/strcat/strncat macros expand to nested
   __builtin___*_chk calls which GIMPLE rejects (confirmed for memcpy:
   a bare memcpy(dst, src, n) call expanded to
   __builtin___memcpy_chk(dst, src, n, __builtin_object_size(dst, 0))
   and broke every cold-CAS-cache stdlib build via List[T].extend,
   investigated 2026-07-15 — the other _FORTIFY_SOURCE-wrapped libc
   functions below are the same class of bug, pre-empted before they
   bite the same way). */
#ifdef sprintf
#undef sprintf
#endif
#ifdef snprintf
#undef snprintf
#endif
#ifdef memcpy
#undef memcpy
#endif
#ifdef memmove
#undef memmove
#endif
#ifdef memset
#undef memset
#endif
#ifdef strcpy
#undef strcpy
#endif
#ifdef strncpy
#undef strncpy
#endif
#ifdef strcat
#undef strcat
#endif
#ifdef strncat
#undef strncat
#endif
/* Undefine exception-name macros from fire_runtime.h that clash with
   Mojo struct/class names in generated code. */
#ifdef StopIteration
#undef StopIteration
#endif
#ifdef ValueError
#undef ValueError
#endif
#ifdef TypeError
#undef TypeError
#endif
#ifdef IndexError
#undef IndexError
#endif
#ifdef KeyError
#undef KeyError
#endif
#ifdef NotImplementedError
#undef NotImplementedError
#endif
void mojo_print(char *str);
/* Mojo built-in type constructors */
#ifndef _MOJO_STUB_String
#ifndef _MOJO_CTOR_STRING
#define _MOJO_CTOR_STRING
int64_t String(...);
#endif
#endif
#ifndef _MOJO_STUB_Int
#ifndef _MOJO_CTOR_INT
#define _MOJO_CTOR_INT
int64_t Int(...);
#endif
#endif
#ifndef _MOJO_STUB_UInt
#ifndef _MOJO_CTOR_UINT
#define _MOJO_CTOR_UINT
int64_t UInt(...);
#endif
#endif
#ifndef _MOJO_STUB_Bool
#ifndef _MOJO_CTOR_BOOL
#define _MOJO_CTOR_BOOL
int64_t Bool(...);
#endif
#endif
#ifndef _MOJO_STUB_Int8
#ifndef _MOJO_CTOR_INT8
#define _MOJO_CTOR_INT8
int64_t Int8(...);
#endif
#endif
#ifndef _MOJO_STUB_Int16
#ifndef _MOJO_CTOR_INT16
#define _MOJO_CTOR_INT16
int64_t Int16(...);
#endif
#endif
#ifndef _MOJO_STUB_Int32
#ifndef _MOJO_CTOR_INT32
#define _MOJO_CTOR_INT32
int64_t Int32(...);
#endif
#endif
#ifndef _MOJO_STUB_Int64
#ifndef _MOJO_CTOR_INT64
#define _MOJO_CTOR_INT64
int64_t Int64(...);
#endif
#endif
#ifndef _MOJO_STUB_UInt8
#ifndef _MOJO_CTOR_UINT8
#define _MOJO_CTOR_UINT8
int64_t UInt8(...);
#endif
#endif
#ifndef _MOJO_STUB_UInt16
#ifndef _MOJO_CTOR_UINT16
#define _MOJO_CTOR_UINT16
int64_t UInt16(...);
#endif
#endif
#ifndef _MOJO_STUB_UInt32
#ifndef _MOJO_CTOR_UINT32
#define _MOJO_CTOR_UINT32
int64_t UInt32(...);
#endif
#endif
#ifndef _MOJO_STUB_UInt64
#ifndef _MOJO_CTOR_UINT64
#define _MOJO_CTOR_UINT64
int64_t UInt64(...);
#endif
#endif
#ifndef _MOJO_STUB_Float16
#ifndef _MOJO_CTOR_FLOAT16
#define _MOJO_CTOR_FLOAT16
int64_t Float16(...);
#endif
#endif
#ifndef _MOJO_STUB_BFloat16
#ifndef _MOJO_CTOR_BFLOAT16
#define _MOJO_CTOR_BFLOAT16
int64_t BFloat16(...);
#endif
#endif
#ifndef _MOJO_STUB_Float32
#ifndef _MOJO_CTOR_FLOAT32
#define _MOJO_CTOR_FLOAT32
int64_t Float32(...);
#endif
#endif
#ifndef _MOJO_STUB_Float64
#ifndef _MOJO_CTOR_FLOAT64
#define _MOJO_CTOR_FLOAT64
int64_t Float64(...);
#endif
#endif
#ifndef _MOJO_STUB_Error
#ifndef _MOJO_CTOR_ERROR
#define _MOJO_CTOR_ERROR
int64_t Error(...);
#endif
#endif

/* Mojo iterator and utility functions */
#ifndef _MOJO_STUB_iter
#define _MOJO_STUB_iter
int64_t iter(...);
#endif
#ifndef _MOJO_STUB_next
#define _MOJO_STUB_next
int64_t next(...);
#endif
#ifndef _MOJO_STUB_swap
#define _MOJO_STUB_swap
void swap(...);
#endif
#ifndef _MOJO_STUB_op
#define _MOJO_STUB_op
int64_t op(...);
#endif
#ifndef _MOJO_STUB_U128
#define _MOJO_STUB_U128
int64_t U128(...);
#endif
#ifndef _MOJO_STUB_Pointer
#define _MOJO_STUB_Pointer
#ifndef _MOJO_POINTER_STRUCT_DEF
int64_t Pointer(...);
#endif
#endif
#ifndef _MOJO_STUB_UnsafePointer
#define _MOJO_STUB_UnsafePointer
int64_t UnsafePointer(...);
#endif
#ifndef _MOJO_STUB_StringSlice
#define _MOJO_STUB_StringSlice
int64_t StringSlice(...);
#endif
#ifndef _MOJO_STUB_StaticString
#define _MOJO_STUB_StaticString
int64_t StaticString(...);
#endif
#ifndef _MOJO_STUB_debug_assert
#define _MOJO_STUB_debug_assert
void debug_assert(...);
#endif
#ifndef _MOJO_STUB___get_mvalue_as_litref
#define _MOJO_STUB___get_mvalue_as_litref
int64_t __get_mvalue_as_litref(...);
#endif
#ifndef _MOJO_STUB___get_litref_as_mvalue
#define _MOJO_STUB___get_litref_as_mvalue
int64_t __get_litref_as_mvalue(...);
#endif
#ifndef _MOJO_STUB_MojoList_unsafe_ptr
#define _MOJO_STUB_MojoList_unsafe_ptr
int64_t MojoList_unsafe_ptr(...);
#endif
#ifndef _MOJO_STUB_MojoList_unsafe_get
#define _MOJO_STUB_MojoList_unsafe_get
int64_t MojoList_unsafe_get(...);
#endif
#ifndef _MOJO_STUB_Span_unsafe_ptr
#define _MOJO_STUB_Span_unsafe_ptr
int64_t Span_unsafe_ptr(...);
#endif
#ifndef _MOJO_STUB_Optional
#define _MOJO_STUB_Optional
int64_t Optional(...);
#endif
#ifndef _MOJO_STUB_int64_t_init_pointee_move
#define _MOJO_STUB_int64_t_init_pointee_move
void int64_t_init_pointee_move(...);
#endif
#ifndef _MOJO_STUB_conforms_to
#define _MOJO_STUB_conforms_to
_Bool conforms_to(int64_t a, int64_t b);
#endif
#ifndef _MOJO_STUB_Codepoint
#define _MOJO_STUB_Codepoint
int64_t Codepoint(...);
#endif
#ifndef _MOJO_STUB_stat_result
#define _MOJO_STUB_stat_result
int64_t stat_result(...);
#endif
#ifndef _MOJO_STUB_UInt128
#define _MOJO_STUB_UInt128
int64_t UInt128(...);
#endif
#ifndef _MOJO_STUB_SIMDSize
#define _MOJO_STUB_SIMDSize
int64_t SIMDSize(...);
#endif
#ifndef _MOJO_STUB_List
#define _MOJO_STUB_List
int64_t List(...);
#endif
#ifndef _MOJO_STUB_MojoDict__reserved
#define _MOJO_STUB_MojoDict__reserved
int64_t MojoDict__reserved(...);
#endif
#ifndef _MOJO_STUB_ord
#define _MOJO_STUB_ord
int64_t ord(...);
#endif
#ifndef _MOJO_STUB_chr
#define _MOJO_STUB_chr
int64_t chr(...);
#endif
#ifndef _MOJO_STUB_sort
#define _MOJO_STUB_sort
void sort(...);
#endif
#ifndef _MOJO_STUB_Span_byte_length
#define _MOJO_STUB_Span_byte_length
int64_t Span_byte_length(...);
#endif
#ifndef _MOJO_STUB__stat_macos
#define _MOJO_STUB__stat_macos
int64_t _stat_macos(...);
#endif
#ifndef _MOJO_STUB__getpw_macos
#define _MOJO_STUB__getpw_macos
int64_t _getpw_macos(...);
#endif
#ifndef _MOJO_STUB_Passwd
#define _MOJO_STUB_Passwd
int64_t Passwd(...);
#endif
#ifndef _MOJO_STUB_create_test_device_context
#define _MOJO_STUB_create_test_device_context
int64_t create_test_device_context(...);
#endif
#ifndef _MOJO_STUB_check_write_to
#define _MOJO_STUB_check_write_to
void check_write_to(...);
#endif
#ifndef _MOJO_STUB__unsupported_mma_op
#define _MOJO_STUB__unsupported_mma_op
void _unsupported_mma_op(...);
#endif
#ifndef _MOJO_STUB_IntType
#define _MOJO_STUB_IntType
int64_t IntType(...);
#endif
#ifndef _MOJO_STUB_Byte
#define _MOJO_STUB_Byte
int64_t Byte(...);
#endif
#ifndef _MOJO_STUB_hash
#define _MOJO_STUB_hash
int64_t hash(...);
#endif
#ifndef _MOJO_STUB_MojoList___contains__
#define _MOJO_STUB_MojoList___contains__
int64_t MojoList___contains__(...);
#endif
#ifndef _MOJO_STUB_MojoList_get_loaded_kgen_pack
#define _MOJO_STUB_MojoList_get_loaded_kgen_pack
int64_t MojoList_get_loaded_kgen_pack(...);
#endif
#ifndef _MOJO_STUB__stat_linux_x86
#define _MOJO_STUB__stat_linux_x86
int64_t _stat_linux_x86(...);
#endif
#ifndef _MOJO_STUB_func
#define _MOJO_STUB_func
int64_t func(...);
#endif
#ifndef _MOJO_STUB_mojo_getenv
#define _MOJO_STUB_mojo_getenv
int64_t mojo_getenv(...);
#endif
#ifndef _MOJO_STUB_mojo_atol
#define _MOJO_STUB_mojo_atol
int64_t mojo_atol(...);
#endif
#ifndef _MOJO_STUB_mojo_frexp
#define _MOJO_STUB_mojo_frexp
int64_t mojo_frexp(...);
#endif
#ifndef _MOJO_STUB_mojo_abort
#define _MOJO_STUB_mojo_abort
void mojo_abort(...);
#endif
#ifndef _MOJO_STUB_Span_as_bytes
#define _MOJO_STUB_Span_as_bytes
int64_t Span_as_bytes(...);
#endif
#ifndef _MOJO_STUB_Span_get_immutable
#define _MOJO_STUB_Span_get_immutable
int64_t Span_get_immutable(...);
#endif
#ifndef _MOJO_STUB__Bool___mlir_i1__
#define _MOJO_STUB__Bool___mlir_i1__
int64_t _Bool___mlir_i1__(...);
#endif
#ifndef _MOJO_STUB_sync_parallelize
#define _MOJO_STUB_sync_parallelize
void sync_parallelize(...);
#endif
#ifndef _MOJO_STUB_main_func
#define _MOJO_STUB_main_func
void main_func(void);
#endif
#ifndef _MOJO_STUB_scalar
#define _MOJO_STUB_scalar
int64_t scalar(...);
#endif
#ifndef _MOJO_STUB_Scalar
#define _MOJO_STUB_Scalar
int64_t Scalar(...);
#endif
#ifndef _MOJO_STUB_type_of
#define _MOJO_STUB_type_of
int64_t type_of(...);
#endif
#ifndef _MOJO_STUB_align_up
#define _MOJO_STUB_align_up
int64_t align_up(...);
#endif
#ifndef _MOJO_STUB_align_down
#define _MOJO_STUB_align_down
int64_t align_down(...);
#endif
#ifndef _MOJO_STUB_clamp
#define _MOJO_STUB_clamp
int64_t clamp(...);
#endif
#ifndef _MOJO_STUB_serialize
#define _MOJO_STUB_serialize
void serialize(...);
#endif
#ifndef _MOJO_STUB_slice
#define _MOJO_STUB_slice
int64_t slice(...);
#endif
#ifndef _MOJO_STUB__getpw_linux
#define _MOJO_STUB__getpw_linux
int64_t _getpw_linux(...);
#endif
#ifndef _MOJO_STUB__lstat_macos
#define _MOJO_STUB__lstat_macos
int64_t _lstat_macos(...);
#endif
#ifndef _MOJO_STUB_getuid
#define _MOJO_STUB_getuid
unsigned int getuid (void);
#endif
#ifndef _MOJO_STUB_getgid
#define _MOJO_STUB_getgid
unsigned int getgid (void);
#endif
#ifndef _MOJO_STUB_getpid
#define _MOJO_STUB_getpid
int getpid (void);
#endif
#ifndef _MOJO_STUB_getppid
#define _MOJO_STUB_getppid
int getppid (void);
#endif
#ifndef _MOJO_STUB_isatty
#define _MOJO_STUB_isatty
int isatty (int fd);
#endif
#ifndef _MOJO_STUB_sysconf
#define _MOJO_STUB_sysconf
long sysconf (int name);
#endif
#ifndef _MOJO_STUB__log2_ceil
#define _MOJO_STUB__log2_ceil
int64_t _log2_ceil(...);
#endif
#ifndef _MOJO_STUB_int64_t_unsafe_value
#define _MOJO_STUB_int64_t_unsafe_value
int64_t int64_t_unsafe_value(...);
#endif
#ifndef _MOJO_STUB_MojoDict_unsafe_ptr
#define _MOJO_STUB_MojoDict_unsafe_ptr
int64_t MojoDict_unsafe_ptr(...);
#endif
#ifndef _MOJO_STUB__Empty_copy
#define _MOJO_STUB__Empty_copy
void _Empty_copy(...);
#endif
#ifndef _MOJO_STUB__get_global_or_null
#define _MOJO_STUB__get_global_or_null
int64_t _get_global_or_null(...);
#endif

/* Struct ___new stubs (for Self(...) call sites) */

/* Renamed C-reserved builtins called without import (e.g. abs→mojo_abs) */


char *gimple_codegen_compile_to_gimple(char *src, int do_imports, char *filename);
char *compile_to_gimple(char *mojo_src, int do_imports, char *filename, int auto_gpu);
int64_t mojo_open_file(char *path);
void *mojo_open(char *filename, char *mode);
int64_t int_write (int64_t, char *);
int64_t int_parse_module (int);
#ifndef _MOJO_UNIMPL_STUBS
#define _MOJO_UNIMPL_STUBS
static char * _ReflectTable_in_dll (int64_t a, int64_t b, char * c) { return (char *)dlsym((void *)b, c); }
static MojoList * _Bool_items (int64_t a) { return mojo_list_new(); }
static int64_t id (int64_t x) { return x; }
#endif

typedef struct AssertStmt {
  int64_t __mojo_type_id;
  int64_t value;
  int64_t msg;
  _Bool is_comptime;
} AssertStmt;
#define _MOJO_STUB_AssertStmt
typedef struct AssignStmt {
  int64_t __mojo_type_id;
  int64_t target;
  int64_t value;
  int64_t line;
  int64_t col;
  int64_t type_ann;
} AssignStmt;
#define _MOJO_STUB_AssignStmt
typedef struct AugAssignStmt {
  int64_t __mojo_type_id;
  int64_t target;
  char * op;
  int64_t value;
} AugAssignStmt;
#define _MOJO_STUB_AugAssignStmt
typedef struct AwaitExpr {
  int64_t __mojo_type_id;
  int64_t value;
} AwaitExpr;
#define _MOJO_STUB_AwaitExpr
typedef struct BoolLiteral {
  int64_t __mojo_type_id;
  _Bool value;
} BoolLiteral;
#define _MOJO_STUB_BoolLiteral
typedef struct BreakStmt {
  int64_t __mojo_type_id;
  int _dummy;
} BreakStmt;
#define _MOJO_STUB_BreakStmt
typedef struct Comprehension {
  int64_t __mojo_type_id;
  char * kind;
  int64_t element;
  int64_t key;
  MojoList * generators;
} Comprehension;
#define _MOJO_STUB_Comprehension
typedef struct ComptimeForStmt {
  int64_t __mojo_type_id;
  char * target;
  int64_t iterable;
  MojoList * body;
} ComptimeForStmt;
#define _MOJO_STUB_ComptimeForStmt
typedef struct ComptimeIfStmt {
  int64_t __mojo_type_id;
  int64_t condition;
  MojoList * then_body;
  MojoList * elifs;
  MojoList * else_body;
} ComptimeIfStmt;
#define _MOJO_STUB_ComptimeIfStmt
typedef struct ComptimeVarStmt {
  int64_t __mojo_type_id;
  char * target;
  int64_t value;
} ComptimeVarStmt;
#define _MOJO_STUB_ComptimeVarStmt
typedef struct ContinueStmt {
  int64_t __mojo_type_id;
  int _dummy;
} ContinueStmt;
#define _MOJO_STUB_ContinueStmt
typedef struct DelStmt {
  int64_t __mojo_type_id;
  MojoList * targets;
} DelStmt;
#define _MOJO_STUB_DelStmt
typedef struct DictExpr {
  int64_t __mojo_type_id;
  MojoList * pairs;
} DictExpr;
#define _MOJO_STUB_DictExpr
typedef struct DictLiteral {
  int64_t __mojo_type_id;
  MojoList * pairs;
} DictLiteral;
#define _MOJO_STUB_DictLiteral
typedef struct EllipsisLiteral {
  int64_t __mojo_type_id;
  int _dummy;
} EllipsisLiteral;
#define _MOJO_STUB_EllipsisLiteral
typedef struct ExprStmt {
  int64_t __mojo_type_id;
  int64_t value;
} ExprStmt;
#define _MOJO_STUB_ExprStmt
typedef struct FloatLiteral {
  int64_t __mojo_type_id;
  double value;
} FloatLiteral;
#define _MOJO_STUB_FloatLiteral
typedef struct ForStmt {
  int64_t __mojo_type_id;
  int64_t target;
  int64_t iterable;
  MojoList * body;
  MojoList * else_body;
  _Bool is_async;
} ForStmt;
#define _MOJO_STUB_ForStmt
typedef struct FromImportStmt {
  int64_t __mojo_type_id;
  char * module;
  MojoList * names;
  _Bool wildcard;
} FromImportStmt;
#define _MOJO_STUB_FromImportStmt
typedef struct FunctionDef {
  int64_t __mojo_type_id;
  char * name;
  MojoList * params;
  int64_t return_type;
  MojoList * body;
  MojoList * decorators;
  MojoDict * param_convs;
  MojoDict * param_has_default;
  MojoDict * param_defaults;
  MojoList * kwonly;
  MojoList * comptime_params;
  _Bool is_generator;
  int64_t yield_bearing_node_ids;
  _Bool is_async;
  MojoList * captures;
  _Bool has_capture_list;
} FunctionDef;
#define _MOJO_STUB_FunctionDef
typedef struct Generator {
  int64_t __mojo_type_id;
  char * target;
  int64_t iterable;
  MojoList * conditions;
  int64_t line;
  int64_t col;
} Generator;
#define _MOJO_STUB_Generator
typedef struct GlobalStmt {
  int64_t __mojo_type_id;
  MojoList * names;
} GlobalStmt;
#define _MOJO_STUB_GlobalStmt
typedef struct IdentExpr {
  int64_t __mojo_type_id;
  char * name;
} IdentExpr;
#define _MOJO_STUB_IdentExpr
typedef struct IfStmt {
  int64_t __mojo_type_id;
  int64_t condition;
  MojoList * then_body;
  MojoList * elifs;
  MojoList * else_body;
} IfStmt;
#define _MOJO_STUB_IfStmt
typedef struct ImagLiteral {
  int64_t __mojo_type_id;
  double value;
} ImagLiteral;
#define _MOJO_STUB_ImagLiteral
typedef struct ImportStmt {
  int64_t __mojo_type_id;
  char * module;
  char * alias;
  MojoList * extra;
} ImportStmt;
#define _MOJO_STUB_ImportStmt
typedef struct IntLiteral {
  int64_t __mojo_type_id;
  int64_t value;
  int64_t line;
  int64_t col;
  char * raw;
} IntLiteral;
#define _MOJO_STUB_IntLiteral
typedef struct LambdaExpr {
  int64_t __mojo_type_id;
  MojoList * params;
  int64_t body;
} LambdaExpr;
#define _MOJO_STUB_LambdaExpr
typedef struct ListExpr {
  int64_t __mojo_type_id;
  MojoList * elements;
} ListExpr;
#define _MOJO_STUB_ListExpr
typedef struct ListLiteral {
  int64_t __mojo_type_id;
  MojoList * elements;
} ListLiteral;
#define _MOJO_STUB_ListLiteral
typedef struct MatchCase {
  int64_t __mojo_type_id;
  MojoList * patterns;
  MojoList * body;
  int64_t guard;
  int64_t line;
  int64_t col;
} MatchCase;
#define _MOJO_STUB_MatchCase
typedef struct MatchStmt {
  int64_t __mojo_type_id;
  int64_t subject;
  MojoList * cases;
} MatchStmt;
#define _MOJO_STUB_MatchStmt
typedef struct MultiAssignStmt {
  int64_t __mojo_type_id;
  MojoList * targets;
  int64_t value;
} MultiAssignStmt;
#define _MOJO_STUB_MultiAssignStmt
typedef struct NoneLiteral {
  int64_t __mojo_type_id;
  int _dummy;
} NoneLiteral;
#define _MOJO_STUB_NoneLiteral
typedef struct PassStmt {
  int64_t __mojo_type_id;
  int _dummy;
} PassStmt;
#define _MOJO_STUB_PassStmt
typedef struct RaiseStmt {
  int64_t __mojo_type_id;
  int64_t value;
} RaiseStmt;
#define _MOJO_STUB_RaiseStmt
typedef struct ReturnStmt {
  int64_t __mojo_type_id;
  int64_t value;
} ReturnStmt;
#define _MOJO_STUB_ReturnStmt
typedef struct SetExpr {
  int64_t __mojo_type_id;
  MojoList * elements;
} SetExpr;
#define _MOJO_STUB_SetExpr
typedef struct SetLiteral {
  int64_t __mojo_type_id;
  MojoList * elements;
} SetLiteral;
#define _MOJO_STUB_SetLiteral
typedef struct SliceExpr {
  int64_t __mojo_type_id;
  int64_t obj;
  int64_t start;
  int64_t stop;
  int64_t step;
} SliceExpr;
#define _MOJO_STUB_SliceExpr
typedef struct Span {
  int64_t __mojo_type_id;
  char * _data;
  int64_t _len;
} Span;
#define _MOJO_STUB_Span
typedef struct StringLiteral {
  int64_t __mojo_type_id;
  char * value;
  int64_t line;
  int64_t col;
  _Bool is_bytes;
  _Bool is_raw;
} StringLiteral;
#define _MOJO_STUB_StringLiteral
typedef struct StructDef {
  int64_t __mojo_type_id;
  char * name;
  MojoList * fields;
  MojoList * methods;
  MojoList * decorators;
  MojoDict * comptime_aliases;
  MojoList * bases;
  int64_t line;
  int64_t col;
  _Bool _fieldwise_ctor_synthesized;
} StructDef;
#define _MOJO_STUB_StructDef
typedef struct SubscriptExpr {
  int64_t __mojo_type_id;
  int64_t obj;
  int64_t index;
  MojoList * attrs;
} SubscriptExpr;
#define _MOJO_STUB_SubscriptExpr
typedef struct TraitDef {
  int64_t __mojo_type_id;
  char * name;
  MojoList * methods;
  MojoList * decorators;
} TraitDef;
#define _MOJO_STUB_TraitDef
typedef struct TryStmt {
  int64_t __mojo_type_id;
  MojoList * body;
  MojoList * handlers;
  MojoList * else_body;
  MojoList * finally_body;
} TryStmt;
#define _MOJO_STUB_TryStmt
typedef struct TstringLiteral {
  int64_t __mojo_type_id;
  char * value;
} TstringLiteral;
#define _MOJO_STUB_TstringLiteral
typedef struct TupleExpr {
  int64_t __mojo_type_id;
  MojoList * elements;
} TupleExpr;
#define _MOJO_STUB_TupleExpr
typedef struct TupleLiteral {
  int64_t __mojo_type_id;
  MojoList * elements;
} TupleLiteral;
#define _MOJO_STUB_TupleLiteral
typedef struct VarDecl {
  int64_t __mojo_type_id;
  char * name;
  int64_t type_ann;
  int64_t value;
} VarDecl;
#define _MOJO_STUB_VarDecl
typedef struct WalrusExpr {
  int64_t __mojo_type_id;
  char * name;
  int64_t value;
} WalrusExpr;
#define _MOJO_STUB_WalrusExpr
typedef struct WhileStmt {
  int64_t __mojo_type_id;
  int64_t condition;
  MojoList * body;
  MojoList * else_body;
} WhileStmt;
#define _MOJO_STUB_WhileStmt
typedef struct WithStmt {
  int64_t __mojo_type_id;
  MojoList * items;
  MojoList * body;
  _Bool is_async;
} WithStmt;
#define _MOJO_STUB_WithStmt
typedef struct YieldExpr {
  int64_t __mojo_type_id;
  int64_t value;
} YieldExpr;
#define _MOJO_STUB_YieldExpr
typedef struct YieldFromExpr {
  int64_t __mojo_type_id;
  int64_t value;
} YieldFromExpr;
#define _MOJO_STUB_YieldFromExpr

static char * _mojo_dispatch_repr (void *);
static char * _mojo_repr_list (MojoList *);
static char * _mojo_repr_dict (MojoDict *);
static char * _mojo_generic_elem_repr (int64_t);
static char * _mojo_repr_pair (MojoList *);
/* Generic reflection dispatch (getattr/setattr/dataclasses.fields/is_dataclass) */
static int64_t _mojo_dispatch_getattr (void *obj, char *attr) {
  int64_t _tag = mojo_read_type_tag_safe((int64_t)(intptr_t)obj);

  return mojo_obj_getattr(obj, attr);
}
static void _mojo_dispatch_setattr (void *obj, char *attr, int64_t val) {
  int64_t _tag = mojo_read_type_tag_safe((int64_t)(intptr_t)obj);

  mojo_setattr(obj, attr, val);
}
static MojoList * _mojo_dispatch_fields (void *obj) {
  int64_t _tag = mojo_read_type_tag_safe((int64_t)(intptr_t)obj);

  return mojo_list_new();
}
static int _mojo_dispatch_is_dataclass (void *obj) {
  int64_t _tag = mojo_read_type_tag_safe((int64_t)(intptr_t)obj);
  static const int64_t _known[] = {0};
  if (_tag == 0) return 0;
  for (size_t _i = 0; _i < sizeof(_known)/sizeof(_known[0]); _i++)
    if (_known[_i] == _tag) return 1;
  return 0;
}

static char * _mojo_dispatch_repr (void *obj) {
  if (!obj) return "None";
  int64_t _tag = mojo_read_type_tag_safe((int64_t)(intptr_t)obj);

  return mojo_repr_obj((int64_t)(intptr_t)obj);
}
static char * _mojo_generic_elem_repr (int64_t val) {
  if (val == 0) return "None";
  if (val > 65536) {
    if (mojo_is_registered_list(val))
      return _mojo_repr_list((MojoList *)(intptr_t)val);
    if (mojo_is_registered_dict(val))
      return _mojo_repr_dict((MojoDict *)(intptr_t)val);
    int64_t _tag = mojo_read_type_tag_safe(val);

    return mojo_repr_str((char *)(intptr_t)val);
  }
  return mojo_repr_int(val);
}
static char * _mojo_repr_list (MojoList *lst) {
  /* A list that carries its own per-slot element kinds — a
     `struct.unpack` result for a format that MIXES int/float/
     bytes fields, or a heterogeneous list literal — describes
     its slots one at a time, and the generic walker below
     cannot: it reads every slot through mojo_list_get_int, so a
     float prints as its raw IEEE-754 bit pattern. The codegen
     picks the kinds-aware helper for a value whose kinds it
     knows statically, but every DERIVED value (list(t), t[:],
     t returned from a function) has no compile-time name to
     look them up by — the runtime recorded them on the value
     itself instead, so ask it here. One failed probe for a
     list with no kinds, which is every other list. */
  if (mojo_list_get_kinds(lst))
    return mojo_repr_list_kinds(lst, 0);
  int _is_tup = lst && mojo_is_tuple(lst);
  if (!lst) return _is_tup ? "()" : "[]";
  int64_t _n = mojo_list_len(lst);
  char *_buf = strdup(_is_tup ? "(" : "[");
  for (int64_t _i = 0; _i < _n; _i++) {
    if (_i > 0) _buf = mojo_str_cat(_buf, ", ");
    int64_t _e = mojo_list_get_int(lst, _i);
    /* The list's own ELEMENT REPR, when the codegen recorded
       one: this list's elements are a registered struct, and the
       generic reader below cannot know that -- a struct-allocated
       value carries no runtime type tag, so _mojo_dispatch_repr
       never finds it and the slot printed as a raw pointer
       decimal (bugs/CODEGEN_user_defined_dunder_repr_not_
       consulted_by_str_and_container_spellings.md). Asked FIRST
       because it is the most specific answer available; NULL
       means this list says nothing and the path below is
       unchanged. */
    char *_re = mojo_list_repr_elem(lst, _e);
    if (_re) { _buf = mojo_str_cat(_buf, _re); free(_re); continue; }
    /* A registered 2-element element is a runtime-built PAIR
       (zip / dict.items() / enumerate) and prints through the
       pair walker, which gets slot 0 right where the generic
       element repr cannot (see _mojo_repr_pair's own comment). */
    _buf = mojo_str_cat(_buf,
      (_e > 65536 && mojo_is_registered_list(_e)
       && mojo_list_len((MojoList *)(intptr_t)_e) == 2)
        ? _mojo_repr_pair((MojoList *)(intptr_t)_e)
        : _mojo_generic_elem_repr(_e));
  }
  if (_is_tup && _n == 1) _buf = mojo_str_cat(_buf, ",");
  return mojo_str_cat(_buf, _is_tup ? ")" : "]");
}
/* One 2-slot pair-list as `(a, b)`. Lives HERE, beside
   _mojo_generic_elem_repr, because it reuses that function's
   value reading (string / list / dict / tagged struct / int)
   rather than keeping a second, drifting copy of it in the
   runtime. The one thing it overrides is slot 0 when the value
   is small: _mojo_generic_elem_repr answers "None" for a 0
   slot, which is right for a genuinely dynamic list (0 can be a
   boxed null there) and wrong for a pair, whose first slot is a
   real value — the 0 INDEX of the first zip/enumerate pair, or a
   small-int dict key. Without this, `zip([0, 1], [2, 3])` printed
   `[(None, 2), (1, 3)]`. A first slot that IS a string (a dict
   key) or a container still goes through the generic reader. */
static char * _mojo_repr_pair (MojoList *p) {
  if (!p) return "()";
  int64_t _n = mojo_list_len(p);
  char *_b = strdup("(" );
  for (int64_t _i = 0; _i < _n; _i++) {
    if (_i > 0) _b = mojo_str_cat(_b, ", ");
    int64_t _v = mojo_list_get_int(p, _i);
    if (_i == 0 && !(_v > 65536))
      _b = mojo_str_cat(_b, mojo_repr_int(_v));
    else
      _b = mojo_str_cat(_b, _mojo_generic_elem_repr(_v));
  }
  if (_n == 1) _b = mojo_str_cat(_b, ",");
  return mojo_str_cat(_b, ")");
}
static char * _mojo_repr_dict (MojoDict *d) {
  if (!d) return "{}";
  char *_buf = strdup("{");
  int64_t *_order = mojo_dict_order_indices(d);
  for (int64_t _oi = 0; _oi < d->used; _oi++) {
    int64_t _i = _order[_oi];
    if (_oi > 0) _buf = mojo_str_cat(_buf, ", ");
    _buf = mojo_str_cat(_buf, mojo_repr_str(mojo_dict_slot_key(d, _i)));
    _buf = mojo_str_cat(_buf, ": ");
    if (d->slots[_i].kind == 3)
      /* A Python bool value (mojo_dict_set_bool): the same 0/1
       * int64_t a real int stores, so only this per-SLOT tag
       * separates them. The tag was once a whole-DICT flag,
       * which meant one bool value reformatted every OTHER
       * value too — `{'name': p.name, 'ok': p.ok}` printed
       * `{'name': True, 'ok': True}`. */
      _buf = mojo_str_cat(_buf, d->slots[_i].val ? "True" : "False");
    else if (d->slots[_i].kind == 2)
      /* A str value stored via mojo_dict_set_str carries its
       * pointer in `val` with kind==2; `_mojo_generic_elem_repr`
       * would read that pointer as an int64_t, so a dict LITERAL's
       * string values printed as garbage/0 (the `param_convs=`
       * / `comptime_aliases=` / `_CONST_NAME` .ast divergence).
       * Emit the real quoted string instead. */
      _buf = mojo_str_cat(_buf, mojo_repr_str((char *)(intptr_t)d->slots[_i].val));
    else
      _buf = mojo_str_cat(_buf, _mojo_generic_elem_repr(d->slots[_i].val));
  }
  free(_order);
  return mojo_str_cat(_buf, "}");
}
static char * _mojo_repr_set (MojoSet *s) {
  if (!s || s->used == 0) return "set()";
  char *_buf = strdup("{");
  int64_t *_order = mojo_set_order_indices(s);
  for (int64_t _oi = 0; _oi < s->used; _oi++) {
    int64_t _i = _order[_oi];
    if (_oi > 0) _buf = mojo_str_cat(_buf, ", ");
    _buf = mojo_str_cat(_buf, s->slots[_i].tag == 1
        ? mojo_repr_str(s->slots[_i].val_s)
        : mojo_repr_int(s->slots[_i].val_i));
  }
  free(_order);
  return mojo_str_cat(_buf, "}");
}


static void _mojo_classattr_init (void);


static int64_t _mojo_dispatch_getattr (void *, char *);
static void _mojo_dispatch_setattr (void *, char *, int64_t);
static MojoList * _mojo_dispatch_fields (void *);
static int _mojo_dispatch_is_dataclass (void *);
static char * _mojo_dispatch_repr (void *);
static char * _mojo_repr_list (MojoList *);
static char * _mojo_repr_dict (MojoDict *);
static char * _mojo_generic_elem_repr (int64_t);

/* String literal globals — array form so address is a compile-time r-value (required by GIMPLE strict mode) */
static char * _slit_10000 = "\n";

int64_t _gimple_main (void)
{
  MojoList * _t1;
  int64_t _t2;
  int64_t _t3;
  MojoList * _t4;
  int64_t _t5;
  int64_t _t6;
  int64_t _t7;
  int64_t _t8;
  int _t9;
  _Bool _t10;
  char * _t11;
  char * _t12;
  MojoList * _t13;
  int64_t _t14;
  int64_t _t15;
  MojoList * _t16;
  int64_t _t17;
  int64_t _t18;
  int64_t _t19;
  int64_t _t20;
  int _t21;
  _Bool _t22;
  char * _t23;
  char * _t24;
  MojoList * _t25;
  int64_t _t26;
  int64_t _t27;
  MojoList * _t28;
  int64_t _t29;
  int64_t _t30;
  int64_t _t31;
  int64_t _t32;
  int _t33;
  _Bool _t34;
  char * _t35;
  char * _t36;
  MojoList * _t37;
  int64_t _t38;
  int64_t _t39;
  MojoList * _t40;
  int64_t _t41;
  int64_t _t42;
  int64_t _t43;
  int64_t _t44;
  int _t45;
  _Bool _t46;
  char * _t47;
  char * _t48;
  MojoList * _t49;
  MojoList * _t50;
  int64_t _t51;
  int64_t _t52;
  int _t53;
  _Bool _t54;
  char * _t55;
  char * _t56;
  MojoList * _t57;
  MojoList * _t58;
  int64_t _t59;
  int64_t _t60;
  int _t61;
  _Bool _t62;
  char * _t63;
  char * _t64;
  int64_t _t65;
  _mojo_classattr_init ();
#line 2
  _t1 = mojo_list_new ();
#line 2
  _t2 = (int64_t)1;
#line 2
  mojo_list_append_int (_t1, _t2);
#line 2
  _t3 = (int64_t)2;
#line 2
  mojo_list_append_int (_t1, _t3);
#line 2
  mojo_mark_as_tuple (_t1);
#line 2
  _t4 = mojo_list_new ();
#line 2
  _t5 = (int64_t)1;
#line 2
  mojo_list_append_int (_t4, _t5);
#line 2
  _t6 = (int64_t)2;
#line 2
  mojo_list_append_int (_t4, _t6);
#line 2
  mojo_mark_as_tuple (_t4);
#line 2
  _t7 = (int64_t)1;
#line 2
  _t8 = (int64_t)1;
#line 2
  _t9 = mojo_list_eq (_t1, _t4, _t7, _t8);
#line 2
  _t10 = _t9 != 0;
#line 2
  _t11 = mojo_repr_bool (_t10);
#line 2
  mojo_print (_t11);
#line 2
  _t12 = _slit_10000;
#line 2
  mojo_print (_t12);
#line 3
  _t13 = mojo_list_new ();
#line 3
  _t14 = (int64_t)1;
#line 3
  mojo_list_append_int (_t13, _t14);
#line 3
  _t15 = (int64_t)2;
#line 3
  mojo_list_append_int (_t13, _t15);
#line 3
  mojo_mark_as_tuple (_t13);
#line 3
  _t16 = mojo_list_new ();
#line 3
  _t17 = (int64_t)1;
#line 3
  mojo_list_append_int (_t16, _t17);
#line 3
  _t18 = (int64_t)3;
#line 3
  mojo_list_append_int (_t16, _t18);
#line 3
  mojo_mark_as_tuple (_t16);
#line 3
  _t19 = (int64_t)1;
#line 3
  _t20 = (int64_t)1;
#line 3
  _t21 = mojo_list_eq (_t13, _t16, _t19, _t20);
#line 3
  _t22 = _t21 != 0;
#line 3
  _t23 = mojo_repr_bool (_t22);
#line 3
  mojo_print (_t23);
#line 3
  _t24 = _slit_10000;
#line 3
  mojo_print (_t24);
#line 4
  _t25 = mojo_list_new ();
#line 4
  _t26 = (int64_t)1;
#line 4
  mojo_list_append_int (_t25, _t26);
#line 4
  _t27 = (int64_t)2;
#line 4
  mojo_list_append_int (_t25, _t27);
#line 4
  mojo_mark_as_tuple (_t25);
#line 4
  _t28 = mojo_list_new ();
#line 4
  _t29 = (int64_t)1;
#line 4
  mojo_list_append_int (_t28, _t29);
#line 4
  _t30 = (int64_t)2;
#line 4
  mojo_list_append_int (_t28, _t30);
#line 4
  _t31 = (int64_t)1;
#line 4
  _t32 = (int64_t)1;
#line 4
  _t33 = mojo_list_eq (_t25, _t28, _t31, _t32);
#line 4
  _t34 = _t33 != 0;
#line 4
  _t35 = mojo_repr_bool (_t34);
#line 4
  mojo_print (_t35);
#line 4
  _t36 = _slit_10000;
#line 4
  mojo_print (_t36);
#line 5
  _t37 = mojo_list_new ();
#line 5
  _t38 = (int64_t)1;
#line 5
  mojo_list_append_int (_t37, _t38);
#line 5
  _t39 = (int64_t)2;
#line 5
  mojo_list_append_int (_t37, _t39);
#line 5
  _t40 = mojo_list_new ();
#line 5
  _t41 = (int64_t)1;
#line 5
  mojo_list_append_int (_t40, _t41);
#line 5
  _t42 = (int64_t)2;
#line 5
  mojo_list_append_int (_t40, _t42);
#line 5
  mojo_mark_as_tuple (_t40);
#line 5
  _t43 = (int64_t)1;
#line 5
  _t44 = (int64_t)1;
#line 5
  _t45 = mojo_list_eq (_t37, _t40, _t43, _t44);
#line 5
  _t46 = _t45 != 0;
#line 5
  _t47 = mojo_repr_bool (_t46);
#line 5
  mojo_print (_t47);
#line 5
  _t48 = _slit_10000;
#line 5
  mojo_print (_t48);
#line 6
  _t49 = mojo_list_new ();
#line 6
  mojo_mark_as_tuple (_t49);
#line 6
  _t50 = mojo_list_new ();
#line 6
  mojo_mark_as_tuple (_t50);
#line 6
  _t51 = (int64_t)1;
#line 6
  _t52 = (int64_t)1;
#line 6
  _t53 = mojo_list_eq (_t49, _t50, _t51, _t52);
#line 6
  _t54 = _t53 != 0;
#line 6
  _t55 = mojo_repr_bool (_t54);
#line 6
  mojo_print (_t55);
#line 6
  _t56 = _slit_10000;
#line 6
  mojo_print (_t56);
#line 7
  _t57 = mojo_list_new ();
#line 7
  mojo_mark_as_tuple (_t57);
#line 7
  _t58 = mojo_list_new ();
#line 7
  _t59 = (int64_t)1;
#line 7
  _t60 = (int64_t)1;
#line 7
  _t61 = mojo_list_eq (_t57, _t58, _t59, _t60);
#line 7
  _t62 = _t61 != 0;
#line 7
  _t63 = mojo_repr_bool (_t62);
#line 7
  mojo_print (_t63);
#line 7
  _t64 = _slit_10000;
#line 7
  mojo_print (_t64);
#line 8
  _t65 = 0LL;
#line 8
  return _t65;
}

int main (int argc, const char **argv) {
  mojo_set_argv(argc, argv);
#if USE_PYTHON
  Py_Initialize ();
#endif
  int64_t result = _gimple_main ();
#if USE_PYTHON
  Py_Finalize ();
#endif
  return result;
}

static void _mojo_classattr_init (void)
{
}

/* No device code in this module, so there is nothing to offload. The
   introspection entry points still exist so a program can ASK whether the
   device path was taken -- which is the question --no-gpu makes worth asking
   -- and get an honest 0. See device_glue.EMPTY_SIDECAR. */
__attribute__((weak)) int64_t _mojo_gpu_kernel_count(void)    { return 0; }
__attribute__((weak)) int64_t _mojo_gpu_have_device(void)     { return 0; }
__attribute__((weak)) int64_t _mojo_gpu_dispatch_count(void)  { return 0; }
__attribute__((weak)) int64_t _mojo_gpu_failure_count(void)   { return 0; }
