#!/usr/bin/env python3
"""Lean 4 proof generation for the x86-64 formal backend.

Ported in structure from /Users/mrs/net/chatgpt/claude/formal/compiler/proof_gen.py
(the toy formal compiler's x86-64 proof generator) and re-targeted from that
project's mini-AST onto fire_compiler nodes, mirroring
formal/arm64_proof_gen.py's emitted-file shape so the two backends' proofs read
alike.

## What is shared and what is not

The source-semantic half of a proof is generated by ONE piece of code — the Lean
model of the program (`<fn>_go`), its simplification lemmas, and the `MojoFunc`
value that mirrors the source AST are all emitted by
`formal/arm64_proof_gen.py` and imported here rather than reimplemented, because
two copies of the model generator would be free to disagree about what a
program means, which is the one thing a two-backend compiler must not have.

**"Architecture-independent" is about the CODE, not about the TEXT, and one
value in the model is a fact about the image rather than about the source.** A
string literal's value on this path is the ADDRESS of its interned bytes, read
off this backend's own intern table (`info["str_addrs"]`, published by
`formal/x86_64_codegen.py`), so the two backends emit the same model of
`return "small"` with a DIFFERENT number in it — and that is correct, because
the number is where the two layouts put the data. What must not differ is the
model's SHAPE, and it does not: one generator, one reader (`_str_addr_term`),
one table per image. The consequence to keep in mind is that a byte comparison
of the two files' model sections is no longer a test — only the shape is.

The MACHINE half is per-architecture, and that is what lives here: the compiled
bytes as a `Nat → UInt8` code function, the certificates relating execution to
the source, and the end-to-end theorem over `X86State` / `x86_exec_exit` — the model
`lib/ProofLib.lean` already carries for x86-64.

## Honesty about what is proved

The per-instruction step certificates are `sorry`. That is deliberate and is
the same trust boundary the arm64 generator starts from: the statement of what
is being claimed is exact (the source model, the AST bridge, the code bytes and
the end-to-end theorem all typecheck and are real), and the part that is not yet
machine-checked is marked as such rather than hidden. A `sorry` in Lean makes
the theorem ACCEPTED, so a `sorry` here is a claim of trust, not a proof — the
audit tooling in the toy project counts exactly these.
"""

from formal.types import (DEFAULT_INT_TYPE, function_var_types,
                          parse_type_name, resolve, uses_typed_model)
from formal.x86_64 import ARG_REGS  # noqa: F401 — read by `_x86_entry`

# The file's own preamble, matching formal/arm64_proof_gen.py's: the deep
# recursion is the model equations and `native_decide` runs, and the linter
# options are off because a generated file legitimately has unused binders in
# the parts that are `sorry`.
_PREAMBLE = """import ProofLib
import work
import Refine

set_option maxRecDepth 100000
set_option maxHeartbeats 20000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
"""

_TRUST_HEADER = (
    "/- The three trust boundaries below are the ones the arm64 backend uses,\n"
    "   stated over the x86-64 machine model in lib/ProofLib.lean:\n"
    "     1. AST   ⟷ the source semantics (`mojo`)  — `eval_eq_mojo`\n"
    "     2. AST   ⟷ the compiled bytes             — `<fn>_compile_correct`\n"
    "     3. bytes ⟷ the executed state             — the step certificates\n"
    "   1 is proved (by the shared generator) for straight-line functions;\n"
    "   2 and 3 are `sorry`, so the end-to-end theorem below inherits their\n"
    "   trust. Read the two as different kinds of remaining hole:\n"
    "     * 2 is `sorry` with a HYPOTHESIS attached. Its `none` branch is\n"
    "       `False` and the run's completing is `hrun`, so what it does not\n"
    "       know is stated rather than absorbed by a `True`.\n"
    "     * 3 is `sorry` only where a certificate would be FALSE — a division\n"
    "       whose divisor is a register, so whether it is zero is what the\n"
    "       program is computing. Those instructions are listed by address\n"
    "       rather than given a claim that cannot hold.\n"
    "   Neither is a proof, and a reader should not take this file as one. -/\n")


def _byte_list(code: bytes, per_line: int = 16) -> str:
    """The compiled bytes as a Lean `List UInt8` literal, wrapped for reading."""
    items = [f"0x{b:02x}" for b in code]
    lines = []
    for i in range(0, len(items), per_line):
        chunk = ", ".join(items[i:i + per_line])
        suffix = "," if i + per_line < len(items) else ""
        lines.append(f"  {chunk}{suffix}")
    return "\n".join(lines) if lines else "  0"


def _code_function(name: str, base: int) -> str:
    """The `<name>_code : Nat → UInt8` the machine model steps through.

    `x86_step` indexes the code function by ABSOLUTE address (`code s.rip`),
    so the function has to map an address back into the image: below the image
    base — and past its end, via `getD` — it reads 0. The base is the image's
    own `base_addr`, not the function's entry, because the image also holds
    the rodata the code addresses absolutely.
    """
    return (f"def {name}_code (addr : Nat) : UInt8 :=\n"
            f"  if addr < {base} then 0\n"
            f"  else {name}_code_bytes.getD (addr - {base}) 0\n")


def _generate_model(prog, fn, tc):
    """The `<fn>_go` model plus the NAMES of its simp lemmas, from the shared
    generator.

    `_gen_go` returns a list of chunks — the model definition and the
    unfolding/recursion lemmas that go with it — which are emitted verbatim.
    `_go_simp_lemmas` returns only the names of the ones safe to add to a
    value-flow simp set, so they are returned separately rather than as text:
    emitting the names as statements produces a file that does not parse, and
    emitting the lemmas twice produces duplicate declarations.  Names go into
    the `eval_eq_mojo` simp set instead, which is where they are wanted.

    `prog` is the whole program, because `_go_defs_for` also emits the models
    of everything `fn` CALLS: a call to a second function in the same program
    names a `f_go` that this file has to define, and defining only `fn`'s own
    model left a call rendering as a reference to nothing.

    Raises whatever the shared generator raises for a shape it does not model;
    the caller degrades to a documented gap rather than failing the build."""
    from formal import arm64_proof_gen as AP
    go_defs = "\n\n".join(AP._go_defs_for(prog, fn, tc))
    return go_defs, list(AP._go_simp_lemmas(fn))

def _first_sentence(e) -> str:
    """Why a probe raised, in one line, for the omission note that quotes it.

    The reasons are written as paragraphs on purpose — they name the limit, the
    measurement and the next step, which is what a reader of the generated file
    needs. A note in the generated file has one line to work with, so this takes
    the first sentence and stops; the rest is in the refusal the build prints.
    """
    text = " ".join(str(e).split())
    head = text.split(". ")[0].strip()
    return (head if head.endswith(".") else head + ".")[:400]


def _ast_value(fn, func_name: str, admitted: dict = None, scope=None) -> str:
    """The `MojoFunc` value mirroring `fn`'s source AST.

    Raises whatever the shared emitter raises for a construct the untyped
    AST model has no form for (a call the bridge cannot resolve, a call of
    another arity, a print, a method call); the caller then drops the bridge
    rather than emitting a value that does not typecheck — and, for a call,
    rather than emitting a value that typechecks into a FALSE theorem.

    The gap check is the shared `arm64_proof_gen._ast_bridge_gaps` and it runs
    BEFORE the translation, because the translation itself cannot detect the
    problem: `_expr_ast`'s `Call` arm renders the first argument and drops the
    rest, so a two-argument call produced a well-typed `ast` whose evaluation
    is not the source's. Measured on `def main(x): return _scalar_max2(x, x)`:
    `eval_eq_mojo` came out `⊢ False` at the bridge's own line, on a program
    of three lines whose every other theorem checked."""
    from formal import arm64_proof_gen as AP
    # The resolvable names are read off the ADMITTED CONTRACTS this generator
    # was handed — the same list it passes to `_call_func_lean` below — rather
    # than off the arm64 generator's spelling→Lean map, because each generator
    # must be consistent with the `callFunc` IT emits and that is the one it
    # builds here.
    resolvable = {func_name} | {c["name"] for c in (admitted or [])
                                if isinstance(c, dict) and c.get("name")}
    gaps = AP._ast_bridge_gaps(fn, resolvable)
    if gaps:
        raise NotImplementedError(AP._ast_gap_message(gaps))
    body = "[" + ", ".join(AP._stmts_ast(fn.body, scope)) + "]"
    # `AP._param_list_lean` and not a local spelling of the parameter list:
    # `MojoFunc.mk` carries the source's parameter NAMES and this backend's
    # `eval_eq_mojo` is the statement that the AST model and the source model
    # are the same function, so the two generators cannot each decide what the
    # AST says a function takes.
    return 'MojoFunc.mk "%s" %s (%s)' % (func_name, AP._param_list_lean(fn), body)


def _eval_eq_mojo_section(func_name: str, fn, typed: bool,
                          go_lemmas: list = None, admitted: dict = None,
                          arity: int = 1, scope=None) -> str:
    """`eval_eq_mojo`: the AST interpreter agrees with the source model.

    Proved for the shapes the shared generator can close by `simp` (a
    straight-line function whose conditions all case-split); `sorry` for the
    rest. A typed (fixed-width) function omits the bridge entirely, as the
    arm64 generator does, because the AST-eval model in ProofLib is untyped.

    Returns None when the AST value itself cannot be built — the caller drops
    the whole section in that case."""
    if typed:
        return ("/- Typed function: the untyped AST-eval bridge is omitted;\n"
                "   correctness follows from the machine value flow. -/\n")
    _ast_value(fn, func_name, admitted, scope)   # probe: may raise
    from formal import arm64_proof_gen as AP
    if AP._is_recursive(fn) or AP._has_while(fn.body):
        return None       # caller emits the `sorry` form
    param = fn.params[0][0] if fn.params else "n"
    # One env entry per SOURCE parameter, each bound to the theorem's binder at
    # the same POSITION.  `{param: param}` bound the first and left every later
    # one unbound, and an unbound name is `0` in `MojoEnv` -- the same
    # first-parameter-only defect this closes, and `AP._entry_arg_names` is the
    # reader both backends use -- so the two cannot bind a different number of
    # parameters than the entry has.
    _sp = [p[0] for p in (fn.params or [])]
    _en = AP._entry_arg_names(arity)
    env = ({_en[i]: _sp[i] for i in range(len(_sp))} if _sp else {})
    # vtypes/call_types, so the `by_cases` conditions and the model's own `if`
    # are the same term, and `sKey` (ProofLib's sign-flip, which is how both
    # render a signed comparison) in the simp set so `simp` sees that the
    # hypothesis IS the model's `if` test.  Same two facts the arm64
    # `eval_eq_mojo` needs; see `_cmp_go`.
    vtypes = function_var_types(fn)
    call_types = {}
    conds = AP._collect_conds(fn, param, env, vtypes, call_types)
    simp_lems = ", ".join(["mojo", "%s_go" % func_name, "ast", "evalFunc",
                           "MojoEnv", "evalBody", "evalBodyEnv", "evalExpr",
                           "u64pow", "u64powGo", "sKey"] + list(go_lemmas or []))
    if not conds:
        proof = f"simp +decide [{simp_lems}]"
    else:
        by_cases = " ".join(f"by_cases h{i} : {c} <;>"
                            for i, c in enumerate(conds))
        hs = ", ".join(f"h{i}" for i in range(len(conds)))
        proof = (f"{by_cases} simp_all +decide [{hs}, {simp_lems}, "
                 "u64_lt_iff_false_of_le, u64_le_iff_false_of_lt]")
    # `AP._call_func_lean` rather than a local spelling: this is the sixth copy
    # of this `fun name arg => ...` and it has to be the same function the arm64
    # generator builds, because `eval_eq_mojo` on both sides is the statement
    # that the AST model and the source model agree — including about what an
    # ADMITTED call means.
    from formal import arm64_proof_gen as AP
    _cf = AP._call_func_lean(func_name, admitted, arity=arity)
    return (f"/-- eval_eq_mojo: AST evaluation agrees with the semantic model. -/\n"
            f"theorem eval_eq_mojo {AP._entry_binders(arity)} :\n"
            f"  evalFunc ast {_cf} {AP._entry_arg_list(_en)} = "
            f"{AP._apply_args('mojo', _en)} := by\n"
            f"  {proof}\n")


def _compile_correct_section(func_name: str, arity: int = 1) -> str:
    """The AST ⟷ compiled-bytes trust boundary.

    `exec_seq` runs the machine model for a bounded number of steps from the
    function's entry, which is the form the toy x86-64 generator used for the
    same boundary. It is not in ProofLib (only the arm64 side has a step
    composition there), so it is emitted into the proof file itself.

    **The `none` branch was `True`, and that was a hole shaped like a proof.**
    The statement quantified over `steps` and matched the run, saying something
    about `rax` when the run produced a state and `True` when it did not — so
    the theorem was trivially true of every program that runs out of fuel,
    which is every program, for large enough `steps`. It read as a claim about
    compiled code and carried no information, which is the same disease as the
    old `DylibExport.Semantics` (`forall observable, ... -> True`) one layer
    up. A reader checking whether this file was honest would have had to notice
    the `True` to know it was not.

    It is now `False`, with the run's completing supplied as a HYPOTHESIS
    (`hrun`). That is a strictly stronger statement in the honest direction: the
    `none` branch is now unreachable *because something was assumed*, and the
    assumption is visible and dischargeable, where before it was discharged by
    asserting `True` about a case nobody had to reach.

    The theorem is still `sorry`. That is the honest part and it is not what
    this round can close: proving the emitted bytes implement the AST is the
    deepest of the three boundaries and is a project, not a patch. What changes
    here is the SHAPE — a remaining hole is now a hypothesis a caller can
    discharge, which is the only form this programme accepts.

    **`mojo arg` and the entry's arity.**  This section states the handler the
    AST is evaluated under as `fun name arg => mojo arg` -- a bare application
    with no name test, which is what it has always said and is a THIRD
    spelling next to `_call_func_lean`.  It is left alone rather than
    consolidated here because this file's proofs are byte-identical
    artifacts in `~/.gmojo` and rewriting a `sorry`'s statement is not worth
    invalidating them.  What DOES have to follow `mojo` is the arity: at two
    parameters `mojo arg` is a function rather than a value and the statement
    does not elaborate.  The remaining arguments are `_` -- universally
    quantified holes -- because this theorem binds no entry arguments of its
    own, which is honest about what it claims (nothing about any particular
    argument) and is absorbed by the `sorry` that is already the whole of
    this theorem's proof."""
    from formal import arm64_proof_gen as AP
    # At arity > 1 the handler needs the LATER arguments from somewhere, and
    # this theorem has no binder for them, so it gains one: an extra binder per
    # argument past the first, and the handler applied to them.  That is the
    # same quantifier the arm64 generator's theorems carry (`eval_eq_mojo`),
    # and at arity one `_extra` is empty and the emitted text is unchanged.
    _extra = " ".join(f"({n} : UInt64)"
                      for n in AP._entry_arg_names(arity)[1:])
    _extra = (_extra + " ") if (arity > 1 and _extra) else ""
    _handler = ("(fun name arg => mojo arg)" if arity <= 1 else
                "(fun name arg => " + AP._apply_args(
                    "mojo", ["arg"] + AP._entry_arg_names(arity)[1:]) + ")")
    return (
        f"/-- Run the machine model for `steps` instructions from the entry. -/\n"
        f"def {func_name}_exec_seq (s : X86State) (code : Nat → UInt8)\n"
        f"    (addr : Nat) (steps : Nat) : Option X86State :=\n"
        f"  match steps with\n"
        f"  | 0 => some s\n"
        f"  | Nat.succ n =>\n"
        f"    match x86_step s (fun i => code (addr + i)) with\n"
        f"    | some s' => {func_name}_exec_seq s' code s'.rip n\n"
        f"    | none => none\n"
        f"\n"
        f"/-- TRUST BOUNDARY: AST ⟷ compiled bytes.\n\n"
        f"    `hrun` is the run's completing, and it is a hypothesis rather than\n"
        f"    an assertion: the theorem below says nothing about a run that stops,\n"
        f"    because nothing is known about where it stopped. The `none` branch\n"
        f"    is `False` and not `True` for that reason -- see the note on\n"
        f"    `_compile_correct_section`. -/\n"
        f"theorem {func_name}_compile_correct {_extra}(e : MojoExpr)\n"
        f"    (env : String → UInt64) (s : X86State)\n"
        f"    (hrun : ∀ steps : Nat,\n"
        f"      ({func_name}_exec_seq s {func_name}_code {func_name}_offset steps).isSome) :\n"
        f"  ∀ steps : Nat,\n"
        f"    match {func_name}_exec_seq s {func_name}_code {func_name}_offset steps with\n"
        f"    | some s' => s'.rax = evalExpr {_handler} e env\n"
        f"    | none => False := by\n"
        f"  sorry\n")



#: Forms whose step is not TOTAL, so a "this always steps" certificate would be
#: false of them.  `x86_step` returns `none` for a division by zero (and for the
#: 128-bit overflow that is the same fault), and the divisor here is a symbolic
#: register, so whether it is zero is not knowable at proof time.  These are
#: skipped with the reason stated rather than given a certificate that cannot
#: be proved — which is the certificate doing its job: it noticed that `div`
#: is not total where a rubber-stamp would not have.
_NON_TOTAL_FORMS = ("group3:div", "group3:idiv")


class _Insn:
    """One decoded instruction, for the per-instruction certificates."""
    __slots__ = ("addr", "form", "text", "bytes")

    def __init__(self, addr, form, text, raw):
        self.addr = addr
        self.form = form
        self.text = text
        self.bytes = raw


#: How many per-instruction certificates to emit.  Each is a `simp` over the
#: decoder, so a very large function (test_simple's entry body is 2052
#: instructions) can exhaust the step budget partway through the list and take
#: the whole proof file down with it.  The cap is stated in the file when it
#: bites, so a truncated list never reads as a complete one.
_MAX_CERTIFICATES = 2000


def _decode_function_body(code: bytes, info: dict, func_offset: int,
                          limit: int = _MAX_CERTIFICATES):
    """Decode the entry function's own instruction stream.

    The startup stub is skipped: the proof is about the function, and the stub
    is the same three instructions in every image.  Decoding stops at the
    string/data pool, whose bytes are not instructions, and is capped so a
    large program cannot produce a proof file with thousands of certificates
    in it.
    """
    from formal import x86_64_decode as DEC
    base = info["base_addr"]
    start = func_offset - base
    strs = [a for name, a in (info.get("labels") or {}).items()
            if name.startswith("str_")]
    end = (min(strs) - base) if strs else len(code)
    if end <= start:
        return [], 0
    try:
        insns = DEC.decode_all(code, start, end)
    except DEC.DecodeError:
        return [], 0           # a data byte inside the code region
    out = []
    for insn in insns[:limit]:
        out.append(_Insn(base + insn.offset, insn.form,
                         code[insn.offset:insn.next_offset].hex(" "),
                         code[insn.offset:insn.next_offset]))
    return out, len(insns)



#: The `simp` set that reduces one instruction of `x86_step`.  Each entry is a
#: decoder helper rather than a step lemma: the certificate below is about the
#: model DECODING an instruction and producing a successor, so it needs the
#: decoder unfolded but nothing about the successor state's contents — which is
#: what keeps it independent of the register values, which are symbolic here.
_STEP_SIMP = (
    "x86_step, x86_step_rex, x86_step_plain, x86_is_rex, x86_get_reg, "
    "x86_set_reg, x86_mem_addr, x86_rm_read, x86_rm_write, x86_flags_sub, "
    "x86_flags_add, x86_flags_logic, x86_msb, x86_trunc32")


def _step_certificate_section(func_name: str, code_len: int, insns: list = None,
                              total: int = None) -> str:
    """Per-instruction execution certificates.

    One theorem per decoded instruction: given a state sitting at that
    instruction's address, `x86_step` decodes it and yields a successor state.
    Together they say the model can execute every instruction the program
    actually contains, at the addresses it actually contains them at — which is
    the local form of what the `_terminates` obligations below assert globally,
    and the thing that makes a run test's failure mean "the model and the
    source disagree" rather than "the model gave up partway".

    They are stated with the register file SYMBOLIC, so nothing is claimed about
    the values: the point is the decode, not the arithmetic. What the successor
    state IS remains the end-to-end theorem's job, which is why that is still a
    `sorry` — the certificates say the program is executable in the model, not
    that it computes the right thing (the run tests say the latter, for
    concrete inputs).

    Also proved here: the byte list in this file is exactly what the assembler
    emitted. Its length is `rfl` because it is a closed literal — a real, if
    small, statement that the file being typechecked is about the code that was
    emitted.
    """
    out = [
        f"/-- The image described above is exactly the {code_len} bytes the\n"
        f"    assembler emitted. -/\n"
        f"theorem {func_name}_code_length :\n"
        f"    {func_name}_code_bytes.length = {code_len} := rfl\n",
    ]
    if not insns:
        out.append(
            f"/- No per-instruction certificates: the image did not decode, so\n"
            f"   there is no instruction stream to make claims about.  The run\n"
            f"   tests below carry the termination obligation instead. -/\n")
        return "\n".join(out)
    out.append(
        f"/- Every instruction of {func_name}, decoded from the bytes above.\n"
        f"   One certificate each: at this address the model decodes this\n"
        f"   instruction and produces a successor state.  The register file is\n"
        f"   left symbolic on purpose — this is about the decode, and what the\n"
        f"   successor IS is the end-to-end theorem's job. -/\n")
    skipped = [i for i in insns if i.form in _NON_TOTAL_FORMS]
    certs = [i for i in insns if i.form not in _NON_TOTAL_FORMS]
    for n, insn in enumerate(certs):
        facts = "".join(
            f"\n  have g{n}_{j} : {func_name}_code {insn.addr + j} = "
            f"0x{b:02x} := by native_decide"
            for j, b in enumerate(insn.bytes))
        hs = ", ".join(["h"] + ["g%d_%d" % (n, j)
                                 for j in range(len(insn.bytes))])
        out.append(
            f"/-- `{insn.form}` at {insn.addr} "
            f"({insn.text}) -/\n"
            f"theorem {func_name}_steps_at_{insn.addr} (s : X86State) "
            f"(h : s.rip = {insn.addr}) :\n"
            f"    (x86_step s {func_name}_code).isSome = true := by{facts}\n"
            f"  simp [{_STEP_SIMP}, {hs}]\n")
    if total is not None and total > len(insns) + len(skipped):
        out.append(
            f"/- TRUNCATED: {func_name} has {total} instructions and this file\n"
            f"   carries certificates for the first {len(insns) + len(skipped)}\n"
            f"   of them.  The cap is there because each certificate is a `simp`\n"
            f"   over the decoder and a large function exhausts the step budget\n"
            f"   partway through.  This is a shorter list, not a shorter claim:\n"
            f"   the run tests below still execute the whole function. -/\n")
    if skipped:
        where = ", ".join(str(i.addr) for i in skipped)
        out.append(
            f"/- NO CERTIFICATE for {len(skipped)} instruction(s) at {where}:\n"
            f"   `x86_step` is not total for them.  A division returns `none` when\n"
            f"   the divisor is zero, and the divisor is a register, so whether it\n"
            f"   is zero is exactly what the program is computing.  Claiming\n"
            f"   otherwise would be claiming something false.  The run tests below\n"
            f"   still cover them at run time. -/\n")
    return "\n".join(out)


# `X86State`'s field names in `formal/x86_64.py`'s `ARG_REGS` order -- SysV's
# RDI, RSI, RDX, RCX, R8, R9.  One list, next to `_x86_entry` which is its only
# reader, and it is asserted against `ARG_REGS` there so the model and the
# emitter cannot number an argument register differently.
_X_FIELD = ("rdi", "rsi", "rdx", "rcx", "r8", "r9")


def _x86_entry(values: list, offset) -> str:
    """`X86State.init` with the entry function's later ARGUMENTS in RSI, RCX...

    One shared reader for the sites that start a run at the entry, because a run
    test and the end-to-end theorem are one statement about one machine and two
    spellings of the start state would be two chances to disagree about what the
    binary was handed.  At arity one it is the bare `X86State.init v offset`,
    which is what those sites have always written (parenthesised, because both
    of them pass it as one term of a larger application): `X86State.init` sets
    `rdi := input` and `rsi := 0`, so one argument needs no `with` clause at
    all.

    `values` are Lean TERMS (`n` or a decimal literal), in argument order, and
    the registers are `formal/x86_64.py`'s `ARG_REGS` -- SysV's RDI, RSI, RDX,
    RCX, R8, R9, the same order the emitter binds a call's arguments in, so the
    model and the image cannot number them differently.  Past six this REFUSES
    rather than inventing an argument: the seventh travels in the CALLER's
    frame, which an `X86State.init` entry state does not have.
    """
    head = f"X86State.init {values[0]} {offset}"
    if len(values) <= 1:
        return f"({head})"
    if len(values) > len(ARG_REGS):
        raise NotImplementedError(
            f"run test: the entry function takes {len(values)} arguments and "
            f"this architecture passes {len(ARG_REGS)} in registers; argument "
            f"{len(ARG_REGS)} and up travel in the caller's frame, which an "
            f"`X86State.init` entry state does not have, so there is nothing "
            f"honest to write here")
    fields = "".join(f"{_X_FIELD[i]} := {values[i]}, " for i in range(1, len(values)))
    return f"({{ {head} with {fields[:-2]} }})"


def _run_tests_section(func_name: str, test_input: int, externs: list = None,
                       placeholder: bool = False, arity: int = 1,
                       entry_values: list = None) -> str:
    """Concrete run tests: the machine model on the real bytes, by evaluation.

    These are not `sorry` and not assertions — `native_decide` executes the
    emitted byte list through `X86State`/`x86_exec_exit` inside Lean's own
    interpreter and checks the value in RAX against the source model.  They
    are the x86-64 counterpart of arm64_proof_gen's `_runs_*` theorems, and
    they are the one part of this file that is genuine evidence about the
    machine: if the code function's base address, the entry offset or the
    model itself were wrong, these would fail to typecheck.

    The exit pc is 0, which works because `X86State.init` leaves the stack
    zeroed: the entry function's own `ret` pops address 0 and `x86_exec_exit`
    stops there.  That is what lets a proof about "what this function
    computes" start at the function's entry and still reach a definite answer,
    with no startup stub and no planted return address.

    Each input gets two obligations and both are needed.  `_terminates_n`
    says the model actually ran the program to its `ret`; `_runs_n` says the
    result is the source model's.  Reporting the value through a helper that
    maps a failed run to 0 (as arm64's `run_result_exit` does) keeps the
    statement a decidable equality — but without the separate termination
    fact, a model that could not execute the program at all would read as
    "result 0" and quietly agree with any model whose answer is 0.  Together
    they fail loudly on an opcode `x86_step` does not decode, which is a real
    gap in `lib/X86.lean` rather than something to paper over.

    `externs` suppresses the whole section for an image that calls out to the
    runtime.  A call to `print` is a branch to a `__TEXT,__stubs` trampoline
    that lives OUTSIDE the image, and the model has no memory for it: the
    branch lands on a byte the model cannot decode, the run stops, and the
    termination obligation fails — for a program whose arithmetic is perfectly
    fine.  Emitting the obligations anyway turns a known limitation into a
    build failure on every program that prints, which is most of them; naming
    the symbols in a comment instead says what is actually true.

    `externs` must therefore be the PROGRAM's calls, not the image's: the
    emitter's own — the stack-floor guard's `exit` trap, in every prologue since
    `e11f066d` — is subtracted by `_program_externs` before it reaches here,
    because that call is one the model provably never executes (the guard's
    `JAE` is always taken; `formal/x86_64_codegen.py::_emit_stack_floor_guard`
    spells out the sequence and the argument).  Reading the trap as a program
    call is what removed every run test from this backend:
    bugs/FORMAL_x86_64_run_tests_are_gone_since_the_stack_floor_guard_emits_exit.md
    """
    if placeholder:
        # The run test's whole value is that it compares the MODEL against the
        # MACHINE.  When the model is a placeholder the comparison is against
        # nothing, and it fails for a reason that has nothing to do with the
        # machine — which would report a codegen or model bug that is not
        # there.  The honest statement is the gap itself.
        return (
            f"/- NO RUN TESTS for {func_name}: the semantic model above is a\n"
            f"   PLACEHOLDER (see the note on it).  A run test would compare the\n"
            f"   machine against that placeholder and fail, which would say\n"
            f"   nothing about either.  Modelling this function's shape is what\n"
            f"   would close it. -/\n")

    if externs:
        syms = ", ".join(sorted(set(externs)))
        return (
            f"/- NO RUN TESTS for {func_name}: the image calls out to the runtime\n"
            f"   ({syms}), and the model has no memory for a `__TEXT,__stubs`\n"
            f"   trampoline.  The branch lands outside the image and the run stops,\n"
            f"   so a termination obligation here would fail on a program whose\n"
            f"   arithmetic is fine.  What the model CAN still check is everything\n"
            f"   up to the call, which is what the per-instruction certificates\n"
            f"   below cover. -/\n")

    # `entry_values` is the entry function's ARGUMENT words as the startup stub
    # materialized them (`model.entry_arg_values`, already widened to `arity`),
    # so a two-parameter entry's run starts from the same RDI/RSI the binary was
    # given.  `X86State.init` zeroes every register past RDI, so one argument is
    # the bare call it has always been.
    from formal import arm64_proof_gen as AP
    vals = [str(v) for v in (entry_values or [test_input])]
    # The HELPER is a function of the arguments, so it starts from the binder
    # names; only the per-instance theorems below start from concrete words.
    names = AP._entry_arg_names(arity)
    _binds = ("(n : UInt64)" if arity <= 1 else
              " ".join(f"({v} : UInt64)" for v in names))

    helper = (
        f"/-- Result register after running the image from the entry (0 if the\n"
        f"    model could not run it to completion). -/\n"
        f"def {func_name}_result {_binds} : UInt64 :=\n"
        f"  match x86_exec_exit {_x86_entry(names, func_name + '_offset')} "
        f"{func_name}_code 0 with\n"
        f"  | some s => s.rax\n"
        f"  | none => 0\n")
    out = [helper]
    for n in dict.fromkeys([test_input, 0, 1, 2, 5]):
        vv = [str(n)] + ["0"] * (arity - 1)
        run = (f"x86_exec_exit {_x86_entry(vv, func_name + '_offset')} "
               f"{func_name}_code 0")
        out.append(
            f"/-- The model runs the image to completion for input {n}. -/\n"
            f"theorem {func_name}_terminates_{n} :\n"
            f"    ({run}).isSome = true := by\n"
            f"  native_decide\n"
            f"\n"
            f"/-- Concrete verification for input {n}, run from the entry. -/\n"
            f"theorem {func_name}_runs_{n} :\n"
            f"    {func_name}_result " + " ".join(vv)
            + " = " + AP._apply_args('mojo', vv) + " := by\n"
            f"  native_decide\n")
    return "\n".join(out) + "\n"


def _program_externs(info: dict) -> list:
    """The extern calls the PROGRAM makes, as symbol names.

    `info["extern_calls"]` is every unbound call the image carries, and
    `info["compiler_traps"]` is the subset this backend emitted as its own — the
    stack-floor guard's `exit`, once per guarded prologue, which `e11f066d` put
    in EVERY image with an entry.  Subtracting it here is what puts the run
    tests back: they are the one part of an x86-64 proof that is evidence about
    the machine rather than about the model, and they were absent from every
    program on this backend until this function existed
    (bugs/FORMAL_x86_64_run_tests_are_gone_since_the_stack_floor_guard_emits_exit.md).

    Subtract by ADDRESS, not by symbol.  An image that both traps and prints
    has two `exit`-vs-`printf` facts to tell apart, and dropping every `exit`
    would also drop the one a `raise` emits (`_emit_diverge` reaches
    `_emit_call_exit` and is deliberately NOT a compiler trap, because the
    program really does get there).

    An image whose `info` has no `compiler_traps` — a dylib, or any emitter that
    predates the key — is read as having none, which is the conservative
    direction: its run tests stay suppressed rather than being restored on a
    call that may be reachable.
    """
    traps = set(info.get("compiler_traps") or ())
    return [e.get("sym") for e in (info.get("extern_calls") or ())
            if e.get("addr") not in traps]


def generate_x86_64_proof(prog, code, info) -> str:
    """Generate a Lean 4 proof file for an x86-64-compiled program.

    `prog` is the flattened function list formal.build produces (read only:
    the functions and their return types), `code` the emitted machine code and
    `info` the codegen's layout record (`base_addr`, `labels`, `func_name`,
    `test_input`, …)."""
    functions = list(getattr(prog, "functions", None) or [])
    if not functions:
        raise ValueError("x86-64 proof generation needs at least one function")
    func_name = info.get("func_name") or functions[0].name
    fn = next((f for f in functions if f.name == func_name), functions[0])
    func_name = fn.name
    base_addr = info["base_addr"]
    func_offset = info.get("func_offset", base_addr)
    test_input = info.get("test_input", 10)
    code = code or b""
    # The entry function's ARGUMENTS, at its arity -- the same facts the arm64
    # generator reads, through the same readers (`AP._entry_arity`,
    # `AP._entry_arg_names`, `formal.model.entry_arg_values`), so the two
    # architectures cannot state a program of different arity.  `AP` is the
    # arm64 generator, which is where the shared readers live; importing it here
    # rather than in each of the six functions below it is the same one-import
    # rule this file already follows, and it was imported INSIDE the
    # `if _admitted:` branch, where every other use found it unbound.
    from formal import arm64_proof_gen as AP
    from formal import model as _M
    arity = AP._entry_arity(fn)
    enames = AP._entry_arg_names(arity)
    # `entry_args` when the codegen published it, and `test_input` when a
    # caller built an `info` dict by hand (a test, a tool reading one
    # function's proof): both are the startup stub's argument values, so
    # either answers the question and `formal/build.py` is the one that widens
    # the list to the arity in every real build.
    entry_values = _M.entry_arg_values(
        info.get("entry_args", info.get("test_input", 10)), arity)

    call_types = {g.name: resolve(parse_type_name(g.return_type)
                                  or DEFAULT_INT_TYPE)
                  for g in functions}
    vtypes = function_var_types(fn, call_types)
    # The decision is `types.uses_typed_model`, shared with arm64's generator
    # and carrying the reasoning for it.
    typed = uses_typed_model(fn, call_types)
    # `str_addrs` is this image's INTERN TABLE, read off the emitter's own map
    # (see `formal/x86_64_codegen.py`).  It is in `tc` for `_scope_of`'s reason:
    # a string literal's value is the ADDRESS of its bytes, which is a fact
    # about the image and not about the source, and `_scope_of` is the one
    # context every value renderer in the shared generator already takes.  The
    # model, the AST bridge and the machine's registers therefore all read the
    # same table, on this backend and on arm64's.
    tc = {"typed": typed, "vtypes": vtypes, "call_types": call_types,
          "str_addrs": dict(info.get("str_addrs") or {})}
    from formal import arm64_proof_gen as _AP
    _vscope = _AP._Scope()
    _vscope.str_addrs = tc["str_addrs"]

    parts = [_PREAMBLE, _TRUST_HEADER]

    # The ADMITTED HOST CONTRACTS this program rests on.  Rendered by
    # `formal/arm64_proof_gen.py`'s `_admitted_lean` and not here, because there
    # is one way this project writes a claim of trust into a generated proof and
    # it is that function: two copies would be free to drift, and the drift would
    # be one backend emitting something the census cannot count.
    _admitted = list(getattr(prog, "admitted", None) or [])
    if _admitted:
        parts.append(AP._admitted_lean(_admitted))

    # ── source semantics ────────────────────────────────────────────
    try:
        go_defs, go_lemma_names = _generate_model(prog, fn, tc)
        model_note = ""
        model_placeholder = False
    except Exception as e:                          # noqa: BLE001
        # The shared model generator does not cover every shape. Rather than
        # failing the build, emit a trivial model and say so: the rest of the
        # file (AST, bytes, certificates) is still real, and the end-to-end
        # theorem is `sorry` regardless, so nothing false is claimed.
        go_defs = (f"def {func_name}_go (n : UInt64) : UInt64 :=\n"
                   f"  n\n")
        model_placeholder = True
        go_lemma_names = []
        model_note = (f"/- NOTE: the shared model generator does not cover "
                      f"this function's shape ({type(e).__name__}: {e}), so "
                      f"the semantic model below is the identity and nothing "
                      f"downstream of it is claimed. -/\n")

    # The shared model generator can EMIT a model that references a function it
    # never defines — a class constructor lowers to `Point_go`, for instance,
    # with no `Point_go` in the output.  That produces a proof that does not
    # typecheck, and the error is a bare "unknown identifier" pointing at a
    # name the reader has never seen.  So the model is checked against itself
    # before it goes in: every `<name>_go` / `<name>_model` it MENTIONS has to
    # be one it DEFINES.  A model that fails this falls back to the
    # placeholder, which is a stated gap rather than a crash.
    if not model_placeholder:
        import re as _re
        defined = set(_re.findall(r"def (\w+)", go_defs))
        defined |= set(_re.findall(r"theorem (\w+)", go_defs))
        referenced = set(_re.findall(r"\b(\w+_(?:go|model))\b", go_defs))
        missing = sorted(referenced - defined)
        if missing:
            model_placeholder = True
            model_note += (
                f"/- NOTE: the generated model refers to {', '.join(missing)}, "
                f"which the shared generator does not define, so the semantic "
                f"model below is the identity and nothing downstream of it is "
                f"claimed. -/\n")
            go_defs = (f"def {func_name}_go (n : UInt64) : UInt64 :=\n"
                       f"  n\n")
            go_lemma_names = []

    parts.append("/-- Mojo semantics: direct Lean model of the source code. -/\n"
                 + model_note + go_defs + "\n")

    # How `mojo` applies the model depends on the model's own signature, so
    # READ it out of the generated definition rather than guessing from which
    # pattern matched.  The guess was wrong for a `for` loop over `range`:
    # `_dec_while_pattern` fires, so the argument became `n.toNat`, while
    # `_gen_go` had produced a UInt64-parameterised model -- a type mismatch
    # that failed the whole proof for a function the model handles perfectly
    # well.  The reader is `_model_shape`, shared with the arm64 generator, so
    # the two cannot drift -- and it handles the NULLARY model
    # (`def ret42_go : UInt64`, a function the source declares with no
    # parameters), which this file's own regex did not match: it defaulted to
    # the argument `n` and emitted `ret42_go n`, which Lean recovers from as a
    # `sorry` so every `native_decide` downstream then failed with "'mojo'
    # uses 'sorry'".
    from formal import arm64_proof_gen as AP
    mojo_term = AP._go_apply(go_defs, func_name, AP._entry_arg_names(arity))
    # The old one-liner verbatim at arity one, which is every program in the
    # corpus: a comment is not semantics, but re-inking it would invalidate
    # every cached verdict in ~/.gmojo for a wording change.
    mojo_note = ("/-- The semantic model as a UInt64 -> UInt64 function. -/\n"
                 if arity <= 1 else
                 f"/-- The semantic model as a function of {func_name}'s "
                 f"{arity} arguments, one per parameter. -/\n")
    parts.append(mojo_note
                 + f"def mojo {AP._entry_binders(arity)} : UInt64 :=\n"
                 + f"  {mojo_term}\n")

    # ── AST bridge ───────────────────────────────────────────────────
    #
    # A PLACEHOLDER model suppresses the bridge as well as the run tests: the
    # bridge claims the AST evaluation agrees with `mojo`, and against the
    # identity fallback that is simply false — `return Point(3)` evaluates to
    # 0 through the call handler while `mojo n` is `n`, so the obligation
    # would be `0 = n`.  Suppressing it says what is true (nothing is claimed)
    # instead of what is unprovable.
    if model_placeholder:
        section = ("/- AST bridge omitted: the semantic model is a "
                   "PLACEHOLDER (see the note on it), so there is no claim "
                   "for the AST evaluation to agree with. -/\n")
    else:
        try:
            section = _eval_eq_mojo_section(func_name, fn, typed,
                                            go_lemma_names, admitted=_admitted,
                                            arity=arity, scope=_vscope)
        except Exception:                           # noqa: BLE001
            section = None
    if section is None:
        # Either the AST value could not be built (a construct the untyped
        # model has no form for) or the shape's bridge is not closed. Both
        # mean the same thing here: omit the bridge and say which.
        #
        # The reason is the RAISED message, not a fixed sentence: this used to
        # be one hard-coded paragraph naming "calls, prints and method calls",
        # which was aspirational for calls — `_expr_ast` rendered every one of
        # them and the false `eval_eq_mojo` reached Lean — and which therefore
        # described a behaviour the code did not have. Quoting the message
        # means a new gap is described by the gap's own words.
        try:
            _ast_value(fn, func_name, _admitted, _vscope)
            reason = ("this function's shape (recursive/looping): the bridge "
                      "is not closed yet")
        except Exception as e:                      # noqa: BLE001
            reason = _first_sentence(e)
        section = (f"/- AST bridge omitted: {reason.rstrip('.')}. Correctness "
                   f"would have to come from the machine value flow alone. -/\n")
    else:
        # Guarded on its own: the probe inside `_eval_eq_mojo_section` sits
        # behind the typed-function early return, so a TYPED function whose
        # body has no AST form reached this unguarded call and raised out of
        # the build instead of omitting the AST.
        try:
            ast_value = _ast_value(fn, func_name, _admitted, _vscope)
        except Exception as e:                      # noqa: BLE001
            section = (f"/- AST omitted: {_first_sentence(e)} -/\n")
        else:
            parts.append(f"/- AST for {func_name} (mirrors source code). -/\n"
                         f"def ast : MojoFunc := {ast_value}\n")
    parts.append(section)

    # ── the compiled image ───────────────────────────────────────────
    parts.append(
        f"/-- The compiled x86-64 image bytes. -/\n"
        f"def {func_name}_code_bytes : List UInt8 :=\n"
        f"[\n{_byte_list(code)}\n]\n"
        f"\n"
        f"/-- Address the function starts at. -/\n"
        f"def {func_name}_offset : Nat := {func_offset}\n"
        f"\n"
        f"/-- The byte at an absolute address (0 outside the image). -/\n"
        f"{_code_function(func_name, base_addr)}")

    parts.append(_compile_correct_section(func_name, arity))
    parts.append(_run_tests_section(
        func_name, test_input,
        _program_externs(info),
        placeholder=model_placeholder,
        arity=arity, entry_values=entry_values))
    _certs, _total = _decode_function_body(code, info, func_offset)
    parts.append(_step_certificate_section(func_name, len(code), _certs, _total))

    # ── end to end ───────────────────────────────────────────────────
    parts.append(
        f"/-- END-TO-END: executing the compiled x86-64 image computes the\n"
        f"    same value as the source semantics, for every input. -/\n"
        f"theorem {func_name}_compiles_correctly {AP._entry_binders(arity)} :\n"
        f"  match x86_exec_exit "
        f"{_x86_entry(enames, func_name + '_offset')} "
        f"{func_name}_code 0 with\n"
        f"  | some s => s.rax = {AP._apply_args('mojo', enames)}\n"
        f"  | none => False := by\n"
        f"  sorry\n")

    return "\n".join(parts)
