#!/usr/bin/env python3
"""
Bootstrap Verification Suite

Tests the complete bootstrap pipeline:
  1. Stage 1 (Python interpreter) compilation
  2. Determinism verification
  3. C code validation
  4. Multi-test coverage
"""

import subprocess
import sys
import hashlib
from pathlib import Path
from datetime import datetime

STAGE1 = 'scripts/stage1_python_interpreter.py'


class BootstrapTest:
    def __init__(self, name, file_path):
        self.name = name
        self.file_path = file_path
        self.stage1_output = None
        self.stage1_hash = None
        self.stage1_lines = 0
        self.errors = []

    def run_stage1(self):
        """Compile using Stage 1 (Python interpreter)."""
        try:
            result = subprocess.run(
                ['python3', STAGE1, self.file_path],
                capture_output=True,
                text=True,
                timeout=10
            )
            if result.returncode != 0:
                self.errors.append(f"Stage 1 failed: {result.stderr[:100]}")
                return False

            self.stage1_output = result.stdout
            self.stage1_lines = len(self.stage1_output.split('\n'))
            self.stage1_hash = hashlib.md5(self.stage1_output.encode()).hexdigest()
            return True
        except Exception as e:
            self.errors.append(f"Stage 1 exception: {e}")
            return False

    def verify_c_code(self):
        """Verify generated C code has required features."""
        if not self.stage1_output:
            self.errors.append("No C code generated")
            return False

        required = [
            '/* Generated by gimple_codegen.py */',
            '__GIMPLE',
            'bb_',
        ]

        missing = [r for r in required if r not in self.stage1_output]
        if missing:
            self.errors.append(f"Missing GIMPLE features: {missing}")
            return False

        return True

    def test_determinism(self):
        """Run Stage 1 twice and verify outputs are identical."""
        try:
            result1 = subprocess.run(
                ['python3', STAGE1, self.file_path],
                capture_output=True,
                text=True,
                timeout=10
            )
            result2 = subprocess.run(
                ['python3', STAGE1, self.file_path],
                capture_output=True,
                text=True,
                timeout=10
            )

            if result1.returncode != 0 or result2.returncode != 0:
                self.errors.append("Determinism test: one or both runs failed")
                return False

            if result1.stdout == result2.stdout:
                return True
            else:
                self.errors.append("Outputs differ on consecutive runs")
                return False
        except Exception as e:
            self.errors.append(f"Determinism test exception: {e}")
            return False

    def status(self):
        """Return status string."""
        if self.errors:
            return "✗ FAILED"
        return "✓ PASS"


def main():
    print("=" * 80)
    print("MOJO BOOTSTRAP VERIFICATION")
    print("=" * 80)
    print(f"Timestamp: {datetime.now().isoformat()}")
    print()

    # Discover tests
    tests_dir = Path('.')
    test_files = sorted(tests_dir.glob('bootstrap_test_*.mojo'))

    if not test_files:
        print("✗ No test files found!")
        return 1

    print(f"Found {len(test_files)} test files:")
    for f in test_files:
        print(f"  - {f.name}")
    print()

    # Run tests
    tests = [BootstrapTest(f.stem, str(f)) for f in test_files]

    print("=" * 80)
    print("STAGE 1 (PYTHON INTERPRETER) TESTS")
    print("=" * 80)

    passed = 0
    failed = 0

    for test in tests:
        print(f"\n{test.name:40s} ", end="", flush=True)

        # Run compilation
        if not test.run_stage1():
            print(f"✗ (compilation failed)")
            failed += 1
            continue

        # Verify C code
        if not test.verify_c_code():
            print(f"✗ (invalid C code)")
            failed += 1
            continue

        # Test determinism
        if not test.test_determinism():
            print(f"✗ (not deterministic)")
            failed += 1
            continue

        # Success
        print(f"✓ ({test.stage1_lines} lines)")
        passed += 1

    # Summary
    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)

    total = len(tests)
    print(f"Tests passed:      {passed}/{total}")
    print(f"Tests failed:      {failed}/{total}")
    print(f"Success rate:      {100*passed//total}%")

    if failed > 0:
        print("\nFailed tests:")
        for test in tests:
            if test.errors:
                print(f"  {test.name}:")
                for error in test.errors:
                    print(f"    - {error}")

    # Bootstrap status
    print()
    print("=" * 80)
    if passed == total:
        print("✓ BOOTSTRAP STAGE 1 VERIFIED")
        print("=" * 80)
        return 0
    else:
        print("✗ BOOTSTRAP STAGE 1 FAILED")
        print("=" * 80)
        return 1


if __name__ == '__main__':
    sys.exit(main())
