#!/usr/bin/env python3
"""Run a single A/B dump (python-interpreted or self-hosted native) for the
aside/bside harness.

One invocation = one file, one side. Called by the ab.mk rules generated by
gen_ab_makefile.py, which is how `make -j20 aside`/`make -j20 bside` get
real per-file parallelism from GNU Make's own job server.

Both fire.py --dump and ./mojoc --dump MUST run with cwd=REPO (confirmed
empirically this session, and already documented in test_ab_native.py's
run_native_dump docstring): the self-host AST-reflection
struct injection for this compiler's OWN source files is sensitive to the
self-hosted binary's CWD (its `__file__` is a synthetic "<bootstrap>", so
`_SELFHOST_DIR` in gimple_codegen.py resolves relative to CWD, not the real
source location). Both sides therefore write their basename-derived output
files (<basename>.ci/.tok/.ast/.pyi) into the SAME repo root regardless of
which file is being compiled — so two files sharing a basename (56 distinct
`__init__.mojo`s in the stdlib alone) running concurrently would corrupt
each other's output. A per-basename flock (.ab_locks/<basename>.lock)
serializes only the colliding subset; distinct basenames still run fully
in parallel via Make's own -j.

The per-file compile is capped AND reserved. This harness is the bounded
per-file alternative the Makefile and `wholeprogram-help` point at, and it is
bounded by TIMEOUT_S and by memory: `make -j20 bside` is twenty concurrent
native compiles, and the corpus deliberately contains this compiler's own
sources, where one `--dump` has been measured at 15-30 GB (see
SELFHOST_TOKENIZE_BLOWUP in tools/suite.py and BLOW.md §0's "NOT closed"
addendum). The ceiling is the `module` class — the same one the three
`bootstrap-stage*-dumps` fanouts give the identical per-file `--dump` — read
from tools/suite.py's MEMCLASS rather than spelled here, so `MEMLIMIT_GB` moves
it and `MEMLIMIT_GB=0` removes it exactly as it does for every job in the suite.

A ceiling alone was not enough, and this file is where that showed up hardest:
a cap bounds ONE process, so twenty of them are twenty times the cap, and on
2026-09-29 the equivalent fanouts ran about thirty at once at 30-43 GB each
until the machine collapsed. So each file also RESERVES its class out of the
one machine-wide budget (`tools/memslot.py`, `memslot.Slot`) before it starts,
and gives it back when it ends. `make -j20` still says how many files may be
ready; the ledger says how many may run, and the answer to the second is 4 on a
96 GB budget. That is also why a hand-run `make -j20 bside` and a running
`make gate` queue behind each other instead of stacking.

The reservation is taken in-process, around the compile only, rather than by
wrapping the whole script with `memslot.py ... --`: the timeout is the
compile's, and a timeout that counted the wait for memory would kill files for
a queue they did not cause. For the same reason it is released before the
artifacts are moved and the meta.json is written, which cost nothing.

One case takes no reservation at all: a sweep run by `tools/suite.py`, whose
`ab-aside`/`ab-bside` jobs have already reserved `program` for the whole
`make` tree and hand it down in MEMSLOT_HELD. A reservation covers the tree it
admitted, so a second one for the same gigabytes would be a second claim on
them — and `make mojoc`, whose recipe is itself a `memslot.py` wrapper, would
deadlock on it. See `memslot.covering`. The hand-run `make -j20 aside` has no
such parent, which is the case this file is for.

**…except that "covered" is the wrong answer for a fan-out, which is what the
second half of that sentence is for.** Twenty children each told "already
accounted for" are twenty processes each permitted its own 24 GB per-file
ceiling, and the ledger's view of the machine while they ran was a single 55 GB
holder — an allowance of up to 480 GB accounted for by 55, which is the
2026-09-29 shape (about thirty processes at 30-43 GB each, every one inside
its own ceiling) and not a bound. So under a suite job this file draws from the
POOL that job's reservation opens (`memslot.Slot(..., pool=True)`): a
sub-ledger capped at the admitting job's own class, which the machine-wide
ledger does not double-count because the pool's usage is inside that
reservation. 55 GB of pool and 24 GB per file means two files at a time, which
is what the hand-run `make -j20 bside` already did by taking its own
reservations. The per-file CEILING is unchanged either way, so no measurement
depends on this; only the number of files running at once does.

A file killed by the ceiling is recorded as such in its meta.json
(`memory_capped`, with the peak memcap saw) instead of being reported as a
compiler failure with an empty .ci: "this file needed more memory than one
file is allowed" and "this file does not compile" are different findings, and
the sweep's output is the only place either can surface.
"""
import argparse
import fcntl
import json
import os
import shutil
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import memslot                                                  # noqa: E402
import procrun                                                   # noqa: E402
import suite                                                     # noqa: E402

LOCK_DIR = os.path.join(REPO, '.ab_locks')
TIMEOUT_S = 120
# The class one file's compile runs under. A `module` is one source file's
# worth of the closure, which is what a single `--dump` of a single file is,
# and it is what the suite gives the per-file bootstrap fanouts.
MEMCLASS = 'module'


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--side', choices=['a', 'b'], required=True,
                     help='a = shim (python3 fire.py), b = self-hosted (mojoc)')
    ap.add_argument('--key', required=True)
    ap.add_argument('--src', required=True)
    args = ap.parse_args()

    out_root = 'aside' if args.side == 'a' else 'bside'
    out_dir = os.path.join(REPO, out_root, os.path.dirname(args.key))
    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(LOCK_DIR, exist_ok=True)

    basename = os.path.splitext(os.path.basename(args.src))[0]
    lock_path = os.path.join(LOCK_DIR, f'{basename}.lock')

    with open(lock_path, 'w') as lockf:
        fcntl.flock(lockf, fcntl.LOCK_EX)
        try:
            _run_locked(args, basename, out_dir)
        finally:
            fcntl.flock(lockf, fcntl.LOCK_UN)
    return 0


def _run_locked(args, basename: str, out_dir: str) -> None:
    # Clear any stale same-basename artifacts before running (e.g. a killed
    # prior attempt) so a leftover file is never mistaken for this run's.
    for ext in ('tok', 'ast', 'ci', 'pyi'):
        p = os.path.join(REPO, f'{basename}.{ext}')
        if os.path.exists(p):
            os.remove(p)

    env = os.environ.copy()
    if args.side == 'a':
        cmd = [sys.executable, os.path.join(REPO, 'fire.py'), '--dump', args.src]
    else:
        env['MOJO_HOME'] = REPO
        cmd = [os.path.join(REPO, 'mojoc'), args.src, '--dump']

    # The ceiling, spelled the one way. ABSOLUTE paths on both, because the
    # compile runs with cwd=REPO while this script may have been invoked from
    # anywhere, and `memcap.py` has to be found before the workload starts.
    limit = suite.memlimit(MEMCLASS)
    label = f'ab-{args.side}:{os.path.relpath(args.src, REPO)}'
    if limit > 0:
        cmd = [sys.executable, os.path.join(HERE, 'memcap.py'),
               '--limit-gb', str(limit), '--label', label, '--'] + cmd

    # …and the reservation, which is what stops twenty of these being twenty
    # times the ceiling. Taken only when there is a ceiling to reserve: under
    # MEMLIMIT_GB=0 there is no number to take, and taking none is the honest
    # reading of "no memory bound anywhere".
    slot = None
    if limit > 0:
        try:
            slot = memslot.Slot(limit, label, pool=True).acquire()
        except ValueError as exc:
            # A class larger than the whole machine budget can never be
            # admitted. Writing that in the meta is better than waiting for a
            # turn that will never come: the sweep is `make -j20` of these, and
            # a queue that cannot drain looks exactly like a hang.
            _write_meta(os.path.join(out_dir, f'{basename}.meta.json'), {
                'rc': 126, 'elapsed_s': 0.0, 'produced': [],
                'memcap_gb': limit, 'peak_gb': None, 'memory_capped': False,
                'reserved_gb': 0, 'waited_for_memory_s': 0,
                'stderr_tail': f'MEMORY: cannot reserve {limit:g} GB — {exc}'})
            open(os.path.join(out_dir, f'{basename}.ci'), 'w').close()
            return

    t0 = time.time()
    stdout = stderr = ''
    proc = None
    try:
        proc = subprocess.Popen(cmd, cwd=REPO, env=env, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, text=True,
                                errors='replace', start_new_session=True)
        if slot is not None:
            slot.note_job(proc.pid)
        stdout, stderr = proc.communicate(timeout=TIMEOUT_S)
        rc = proc.returncode
    except subprocess.TimeoutExpired:
        rc, stderr = -1, f'TIMEOUT after {TIMEOUT_S}s'
        if proc is not None:
            procrun.kill_group(proc)
    finally:
        # Given back as soon as the compile is over, before the artifacts are
        # moved and the meta is written, so the sweep's next file starts while
        # this one is still tidying up. `memcap`'s own process is gone by then
        # too, which is what makes the release safe: the ceiling that backed
        # the reservation has already stopped the tree.
        if slot is not None:
            slot.release()
    # memcap reports on stdout, which this harness does not otherwise keep, and
    # its two facts are the ones a per-file verdict needs: was this file killed
    # for memory, and how much did it ask for while it ran.
    breached, peak = procrun.memcap_verdict(stdout)

    produced = []
    for ext in ('tok', 'ast', 'ci', 'pyi'):
        src_p = os.path.join(REPO, f'{basename}.{ext}')
        if os.path.exists(src_p):
            shutil.move(src_p, os.path.join(out_dir, f'{basename}.{ext}'))
            produced.append(ext)

    meta = {
        'rc': rc,
        'elapsed_s': round(time.time() - t0, 2),
        'produced': produced,
        'stderr_tail': stderr[-2000:] if stderr else '',
        'reserved_gb': limit if slot is not None else 0,
        'waited_for_memory_s': round(slot.waited, 2) if slot is not None else 0,
    }
    if limit > 0:
        # Always recorded, not only on a kill: a sweep that answers "which
        # files are close to the ceiling" is the only way to tell whether
        # `module` is the right class for this corpus before someone has to
        # guess again. `reserved_gb`/`waited_for_memory_s` answer the same
        # question for the class as a RESERVATION — how much of it this corpus
        # actually needs when the machine can give it.
        meta['memcap_gb'] = limit
        meta['peak_gb'] = peak
        meta['memory_capped'] = breached
    if breached:
        # Readable in `ab_compare.py`'s failure listing, and not confusable with
        # a compiler error: this file was killed before it said anything.
        meta['stderr_tail'] = (f'MEMORY: killed at the {limit:g} GB per-file '
                               f'ceiling (peak {peak} GB) — not a compile '
                               f'failure' + ('\n' + meta['stderr_tail']
                                             if meta['stderr_tail'] else ''))
    _write_meta(os.path.join(out_dir, f'{basename}.meta.json'), meta)

    # Always leave a .ci target behind (even empty, on failure/timeout) so
    # Make treats this rule as done and doesn't re-run it on every
    # `make aside`/`make bside` — this harness is meant to sweep once, then
    # individual files get fixed and re-tested by hand (see
    # tools/README_ab_harness.md if present, or the Makefile comment).
    ci_path = os.path.join(out_dir, f'{basename}.ci')
    if not os.path.exists(ci_path):
        open(ci_path, 'w').close()


def _write_meta(path, meta):
    """The meta.json write, from both the refused and the normal exit.

    Temp file + rename, because a sweep running twenty of these in parallel
    can be interrupted at any moment, and a half-written meta.json is a
    truncated JSON document that `tools/ab_compare.py` then has to survive.
    """
    tmp = f'{path}.tmp{os.getpid()}'
    with open(tmp, 'w') as mf:
        json.dump(meta, mf)
    os.replace(tmp, path)


if __name__ == '__main__':
    sys.exit(main())
