#!/usr/bin/env python3
"""Run a single A/B dump (shim or self-hosted) for the aside/bside harness.

One invocation = one file, one side. Called by the ab.mk rules generated by
gen_ab_makefile.py, which is how `make -j20 aside`/`make -j20 bside` get
real per-file parallelism from GNU Make's own job server.

Both mojo.py --dump and MOJO_NO_SHIM=1 ./mojoc --dump MUST run with
cwd=REPO (confirmed empirically this session, and already documented in
test_ab_shim.py's run_native_dump docstring): the self-host AST-reflection
struct injection for this compiler's OWN source files is sensitive to the
self-hosted binary's CWD (its `__file__` is a synthetic "<bootstrap>", so
`_SELFHOST_DIR` in gimple_codegen.py resolves relative to CWD, not the real
source location). Both sides therefore write their basename-derived output
files (<basename>.ci/.tok/.ast/.pyi) into the SAME repo root regardless of
which file is being compiled — so two files sharing a basename (56 distinct
`__init__.mojo`s in the stdlib alone) running concurrently would corrupt
each other's output. A per-basename flock (.ab_locks/<basename>.lock)
serializes only the colliding subset; distinct basenames still run fully
in parallel via Make's own -j.
"""
import argparse
import fcntl
import json
import os
import shutil
import subprocess
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCK_DIR = os.path.join(REPO, '.ab_locks')
TIMEOUT_S = 120


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--side', choices=['a', 'b'], required=True,
                     help='a = shim (python3 mojo.py), b = self-hosted (mojoc)')
    ap.add_argument('--key', required=True)
    ap.add_argument('--src', required=True)
    args = ap.parse_args()

    out_root = 'aside' if args.side == 'a' else 'bside'
    out_dir = os.path.join(REPO, out_root, os.path.dirname(args.key))
    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(LOCK_DIR, exist_ok=True)

    basename = os.path.splitext(os.path.basename(args.src))[0]
    lock_path = os.path.join(LOCK_DIR, f'{basename}.lock')

    with open(lock_path, 'w') as lockf:
        fcntl.flock(lockf, fcntl.LOCK_EX)
        try:
            _run_locked(args, basename, out_dir)
        finally:
            fcntl.flock(lockf, fcntl.LOCK_UN)
    return 0


def _run_locked(args, basename: str, out_dir: str) -> None:
    # Clear any stale same-basename artifacts before running (e.g. a killed
    # prior attempt) so a leftover file is never mistaken for this run's.
    for ext in ('tok', 'ast', 'ci', 'pyi'):
        p = os.path.join(REPO, f'{basename}.{ext}')
        if os.path.exists(p):
            os.remove(p)

    env = os.environ.copy()
    if args.side == 'a':
        cmd = [sys.executable, os.path.join(REPO, 'mojo.py'), '--dump', args.src]
    else:
        env['MOJO_NO_SHIM'] = '1'
        env['MOJO_HOME'] = REPO
        cmd = [os.path.join(REPO, 'mojoc'), args.src, '--dump']

    t0 = time.time()
    try:
        result = subprocess.run(cmd, cwd=REPO, env=env,
                                 capture_output=True, text=True,
                                 timeout=TIMEOUT_S, errors='replace')
        rc, stderr = result.returncode, result.stderr
    except subprocess.TimeoutExpired:
        rc, stderr = -1, f'TIMEOUT after {TIMEOUT_S}s'

    produced = []
    for ext in ('tok', 'ast', 'ci', 'pyi'):
        src_p = os.path.join(REPO, f'{basename}.{ext}')
        if os.path.exists(src_p):
            shutil.move(src_p, os.path.join(out_dir, f'{basename}.{ext}'))
            produced.append(ext)

    meta = {
        'rc': rc,
        'elapsed_s': round(time.time() - t0, 2),
        'produced': produced,
        'stderr_tail': stderr[-2000:] if stderr else '',
    }
    with open(os.path.join(out_dir, f'{basename}.meta.json'), 'w') as mf:
        json.dump(meta, mf)

    # Always leave a .ci target behind (even empty, on failure/timeout) so
    # Make treats this rule as done and doesn't re-run it on every
    # `make aside`/`make bside` — this harness is meant to sweep once, then
    # individual files get fixed and re-tested by hand (see
    # tools/README_ab_harness.md if present, or the Makefile comment).
    ci_path = os.path.join(out_dir, f'{basename}.ci')
    if not os.path.exists(ci_path):
        open(ci_path, 'w').close()


if __name__ == '__main__':
    sys.exit(main())
