"""Per-file ceilings for `tools/dangling_doc_refs.py --ratchet`.

GENERATED by `python3 tools/dangling_doc_refs.py --write-baseline`. Do not
hand-edit: a file listed here is one whose citations of DELETED bug docs this
tree still carries, and the number is what it carried when the ledger was last
regenerated. The ratchet fails when a file EXCEEDS its number, so a file that
fixes its citations needs no entry change, and an entry may be removed once the
file has none.

Two entries are deliberate rather than unfixed, and are the reason this ledger
is a `.py` and not a JSON:

`test_suite.py` names documents that do not exist (`NEVER_WRITTEN.md`,
`NO_SUCH_DOC_ANYWHERE.md`, `DELETED_ONCE.md`, `SOME.md`) to PROVE the marker
checks can fail. A walk for missing files is guaranteed to find one there. That
also makes them the one thing in this tree a citation SWEEP must not rewrite:
they are the negative controls, so "this name does not resolve" is the property
under test, and a sweep that turned them into prose would silently delete the
proof while leaving the check green. `tools/suite.py` cites a `.md` path as a
fixture for the same reason.

THE LEDGER ITSELF (`tools/dangling_refs_baseline.py`) is EXCLUDED from the
walk, and it is excluded rather than entered because an entry for it cannot
mean anything. Its whole content is the set of doc names other files still
cite, so its own dangling-citation count is a function of what every OTHER
file has been cleaned up to — it moves when a sweep lands, it moves when the
compiler changes which docs exist, and `--write-baseline` would have to record
its own pre-write number. That is not a ceiling, it is a snapshot of the
ledger in the ledger. `test_suite.py` and `tools/suite.py` stay IN, because
their fixtures are a fixed, small, intentional number that a ceiling can
honestly bound.
"""
BASELINE = {
    'bugs/CODEGEN_arm64_cmp_flags_and_loop_signedness.md': 1,
    'test_suite.py': 6,
}
