#!/usr/bin/env python3
"""formal_doc_index.py -- the DERIVED triage index for `bugs/`'s formal documents.

    python3 tools/formal_doc_index.py             # the index, as markdown
    python3 tools/formal_doc_index.py --json      # machine-readable
    python3 tools/formal_doc_index.py --check     # is OPEN_WORK.md's block current?
    python3 tools/formal_doc_index.py --write     # rewrite OPEN_WORK.md's block

`bugs/OPEN_WORK.md`'s formal section was a hand-maintained table, and it was
wrong in the way a hand-maintained table is: it named documents that had been
deleted, it carried prose that no worker re-read, and it had no way to notice
any of that. CLAUDE.md's own argument applies to it directly — *"a tally is not
a property of the tree"* — and it had drifted from "one row per open item" to a
mixture of live rows, `*(deleted 2026-10-02)*` rows explaining a fix in three
sentences, and rows whose subject was three refusals deeper than the row said.

This tool computes the index instead, from two facts about the tree rather than
from a person's memory:

**CLAIM STATUS** comes from `tools/control.py`'s registry (`<git-common-dir>/
control/tasks.json`), read directly rather than by parsing `claims` output. A
task in a terminal state (`integrated`, `abandoned`, `superseded`) has released
its claims, which is the fact the index cares about: **a document whose owning
worker has finished is not being worked on**, and the queue's most expensive
failure is a row that names an owner nobody holds. That is why the index prints
`unclaimed` rather than inventing an owner.

**AREA** is derived from the `formal/` source files each document names: the
`formal/` file it cites most often decides, and only its directory part is kept
— so `formal/arm64.py` and `formal/arm64_proof_gen.py` are two areas, not one,
and `--json` prints the runner-up and its count so the grouping can be argued
with. That is the axis a triage index actually wants ("which part of the
backend is this in"), and it is derived, so it cannot rot: delete a document and
every other document's area is unchanged; move a source file and the areas
follow it. The two fallbacks are an explicit `**Area:** …` line in the document
(the convention about half the corpus already uses) and `unclassified`, which is
a real answer rather than a silent one.

**WHAT A DOC IS** is its own title, which in this corpus is the sentence the
document maintains about itself.

`--check` is what makes the index unable to rot: it renders the block and
compares it with the marked region of `bugs/OPEN_WORK.md`, byte for byte, and
exits 1 on any difference. So adding a document, deleting one, or a worker
starting and finishing changes the index, and the file says so until somebody
runs `--write`.

**And the comparison deliberately EXCLUDES the claim column**, which is the one
part of the block that is a fact about the MACHINE rather than about the tree.
CLAUDE.md's rule is explicit that a check which goes red on branches that did
nothing wrong is worse than no check, because a red check is indistinguishable
from a real regression — and this tree is worked from a dozen worktrees at once,
so *every* one of them starts or finishes a task while the others are mid-run.
Two workers' branches would disagree about the claim column legitimately. So
`--check` compares the document list, the areas, the titles and the counts, and
REPORTS the claim column's drift as a number with `--write` suggested; `--strict`
asks for the full byte comparison when that is what you want.

That split is the same one CLAUDE.md draws between a per-file ceiling and the
machine: the tree's facts are checked, the machine's are displayed.
`test_suite.py` runs `--check`, which puts it in the `check` bucket through the
existing job rather than a new registration.
"""
import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

BUGS = os.path.join(ROOT, 'bugs')
OPEN_WORK = os.path.join(BUGS, 'OPEN_WORK.md')

# The markers delimiting the generated region inside OPEN_WORK.md. They are
# written with the tool's own name in them so a reader who finds the block knows
# what produced it without opening this file, and so `--write` is idempotent.
BEGIN = '<!-- BEGIN generated by tools/formal_doc_index.py -->'
END = '<!-- END generated by tools/formal_doc_index.py -->'

# A document is in the index if its name says so, or if it says so about
# itself. Both halves are checked because this corpus has ~40 documents about the
# formal backend that do not start with `FORMAL_` (`LEAN_*`, `PERF_formal_*`,
# `TEST_formal_*`, `INFRA_*` — the interpreter one), and an index that listed
# only the `FORMAL_` prefix would omit exactly the documents a new worker is
# most likely to trip over.
NAME_PREFIXES = ('FORMAL_', 'LEAN_')
AREA_LINE = re.compile(r'^\s*\**\s*Area:\**\s*(.+?)\s*$', re.I | re.M)
FORMAL_IN_AREA = re.compile(r'\bformal\b', re.I)


def doc_text(path):
    with open(path, encoding='utf-8', errors='replace') as f:
        return f.read()


def is_formal(name, text):
    """Does this document belong in the formal index?"""
    if name.startswith(NAME_PREFIXES):
        return True
    m = AREA_LINE.search(text)
    return bool(m and FORMAL_IN_AREA.search(m.group(1)))


def declared_area(text):
    """The `**Area:** …` line's value, or None. Never guessed from the prose."""
    m = AREA_LINE.search(text)
    return m.group(1) if m else None


def headline(text):
    """The document's own title, with its name stripped off the front.

    **The title, not the opening sentence.** This corpus states what a document
    is in its title and carefully — "A struct-typed FIELD cannot be initialised
    from an argument, and a struct PARAMETER cannot be stored in one" — while
    its opening paragraph is a bolded lead-in that frequently continues a
    sentence from the section above it, so a first-sentence extractor returns
    fragments ("through fire_compiler.py::genexp_body and their own
    _emit_compr_gen-shaped walks)"). Extracting prose here was tried and
    dropped: it is a parser with a failure mode, feeding a column nobody reads,
    and the title is the sentence the document already maintains.

    The document's own name is stripped so the column does not repeat the row
    label — every title in this corpus is spelled `NAME: what it is` or
    `NAME — what it is`. A title that does not match that shape is returned
    whole rather than mangled.
    """
    # A wrapped title: this corpus hand-wraps long ones and keeps the `# ` on
    # every visual line (`# \`raise SystemExit(n)\` for a computed \`n\` leaves
    # status 1, which is not the` / `# program's own`), so the title is the
    # first CONTIGUOUS run of `# ` lines and not the first one.
    run = []
    for line in text.splitlines():
        if line.startswith('# '):
            run.append(line[2:].strip())
        elif run:
            break
    title = ' '.join(run)
    name = title.split(':', 1)[0].split(' — ', 1)[0].split(' - ', 1)[0].strip()
    if name and title != name and re.fullmatch(r'[A-Z][A-Za-z0-9_]*', name):
        rest = title[len(name):].lstrip(' :-—')
        if rest:
            title = rest
    return title or '(untitled)'


def formal_sources(text):
    """Every `formal/…` path the document names, as (directory, file) pairs.

    Deliberately a citation count and not an import graph: the question is "which
    part of the backend does this document talk about", and a document that
    mentions `formal/build.py` twice and `formal/model.py` once is a
    `build.py` document for triage purposes.
    """
    out = []
    for m in re.finditer(r'\bformal/([A-Za-z0-9_]+(?:/[A-Za-z0-9_]+)?'
                         r'[A-Za-z0-9_]*\.py)\b', text):
        out.append(m.group(1))
    return out


def area_of(text):
    """(area, runner-up, how) — derived, with the derivation recorded.

    `how` is `sources` when the area came from the cited files, `declared` when
    it came from an `**Area:**` line, and `unclassified` when neither answered.
    The index prints it, because an index whose grouping nobody can check is a
    hand-maintained table with extra steps.
    """
    counts = {}
    for rel in formal_sources(text):
        counts[rel] = counts.get(rel, 0) + 1
    if counts:
        ranked = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
        top, top_n = ranked[0]
        second = ranked[1] if len(ranked) > 1 else None
        # A directory wins over a file inside it: `formal/arm64.py` is the arm64
        # generator and `formal/arm64_proof_gen.py` is its proof half, and
        # grouping by first path segment keeps them together, which is what a
        # reader wants when deciding who to hand a row to.
        area = 'formal/' + top.split('/', 1)[0].replace('.py', '')
        return area, second, 'sources'
    declared = declared_area(text)
    if declared:
        head = declared.split('(')[0].strip().strip('*` ')
        return head, None, 'declared'
    return 'unclassified', None, 'unclassified'


def live_claims():
    """{doc_stem: [worker, …]} for every claim a NON-terminal task holds.

    Read from the registry rather than from `claims` output, so a claim's
    spelling is the registry's and not a line format. `control.load()` returns
    `{}` when there is no registry, which is the right answer on a checkout with
    no controller: everything is unclaimed and the index says so.
    """
    import control
    tasks = control.load()
    out = {}
    for name, task in sorted(tasks.items()):
        if task.get('state') in control.TERMINAL:
            continue
        for claim in task.get('claims') or ():
            parts = claim.split(':', 1)
            key = parts[1] if len(parts) > 1 else parts[0]
            if key.endswith('.md'):
                key = key[:-3]
            out.setdefault(key, []).append(name)
    return out


def rows():
    """[(name, area, runner_up, how, claimed_by, title)] — sorted."""
    claims = live_claims()
    out = []
    for name in sorted(os.listdir(BUGS)):
        if not name.endswith('.md') or name == 'OPEN_WORK.md':
            continue
        path = os.path.join(BUGS, name)
        text = doc_text(path)
        if not is_formal(name[:-3], text):
            continue
        area, second, how = area_of(text)
        out.append((name[:-3], area, second, how,
                    sorted(claims.get(name[:-3], ())), headline(text)))
    return out


def render():
    """The markdown block. One table per area, plus the counts."""
    data = rows()
    claimed = [r for r in data if r[4]]
    lines = [
        BEGIN,
        '',
        f'**{len(data)} documents about the formal backend, '
        f'{len(claimed)} of them CLAIMED by a live task and '
        f'{len(data) - len(claimed)} UNCLAIMED.** Generated by '
        '`python3 tools/formal_doc_index.py --write`; '
        '`python3 tools/formal_doc_index.py --check` is what keeps it true, and '
        '`test_suite.py` runs that check. **The two columns a reader needs are '
        'AREA (derived from the `formal/` files each document names) and '
        'CLAIMED BY (read from `tools/control.py`\'s registry, so a row whose '
        'worker has finished says `unclaimed` rather than naming an owner nobody '
        "holds).** The third column is the document's OWN title and nothing "
        "else, for the same reason: a row that explains itself in a sentence "
        "is a second copy of the document, and this table is the thing that "
        "goes stale.",
        '',
    ]
    by_area = {}
    for r in data:
        by_area.setdefault(r[1], []).append(r)
    for area in sorted(by_area):
        group = sorted(by_area[area], key=lambda r: (not r[4], r[0]))
        n_claimed = sum(1 for r in group if r[4])
        plural = '' if len(group) == 1 else 's'
        lines.append(f'### `{area}` — {len(group)} document{plural}, '
                     f'{n_claimed} claimed')
        lines.append('')
        lines.append('| doc | claim | what it is (its own title) |')
        lines.append('|---|---|---|')
        for name, _area, _second, how, owners, title in group:
            claim = ', '.join(f'`{o}`' for o in owners) if owners else '**unclaimed**'
            lines.append(f'| `{name}.md` | {claim} | {title} |')
        lines.append('')
    lines.append('---')
    lines.append('')
    lines.append(
        f'**{len(data)} documents, {len(claimed)} claimed.** The unclaimed ones '
        f'are the queue; a claimed one belongs to whoever holds the claim and '
        f'should not be worked from here (`python3 tools/control.py claims` is '
        f'the authority, and this table is derived from the same registry). '
        f'**When a document is deleted this table is wrong until '
        f'`--write` runs**, which is the one failure mode the index cannot '
        f'design away — it can only be checked, so it is checked.')
    lines.append('')
    lines.append(END)
    return '\n'.join(lines)


def open_work_text():
    return doc_text(OPEN_WORK)


def block_in(text):
    """The generated region of OPEN_WORK.md, or None."""
    i = text.find(BEGIN)
    j = text.find(END)
    if i < 0 or j < 0 or j < i:
        return None
    return text[i:j + len(END)]


# The claim column, blanked.
#
# STRUCTURAL, not a regex over the whole line. A regex was tried and it is wrong
# in two ways at once: it blanks the doc-name cell (which is also a backticked
# token followed by a `|`), and it blanks backticked words inside the TITLE
# column — so "neither is in `FORMAL_x86_64_end_to_end_proof`" became "neither is
# in `—`" and the comparison stopped being about the claim column. Only a table
# row's SECOND cell is the claim, so only that cell is replaced.
def _is_row(line):
    """A table row of the generated block, as opposed to its header."""
    return line.startswith('| `') and line.count('|') >= 4


def without_claims(block):
    """The block with the CLAIMED-BY cell of every row blanked, and the two
    counts that are functions of it.

    Blanked: each row's second cell, the per-area "N claimed", and the
    "N documents, M claimed" in the header. NOT blanked: the document list, the
    areas, the titles, the total — those are facts about the tree and they are
    what `--check` is for.

    **The rows are also put back in NAME order**, and that is the second half
    of "ignoring the claim column" rather than an extra strictness. `render()`
    sorts each area by `(not claimed_by, name)` — claimed first, because a
    claimed document belongs to whoever holds it — so WHICH documents are live
    decides the ORDER, and blanking the cell does not put the order back. The
    consequence was that a worker starting or finishing turned
    `formal doc index: OPEN_WORK.md's generated block is current` red with a
    document list that had not changed by one row, and took
    `test_suite.py`'s other two `formal doc index` checks down with it (the
    reduction probe compares the planted block against `render()`, and
    "the file is byte-identical afterwards" asserts `--check` exits 0). Measured
    2026-10-05 on a merge whose only change to the tree was three new files in
    `tools/`: `--check` red, `--write` then green, `--check` red again within the
    hour as the queue turned over, with nothing about `bugs/` edited at all.

    Sorting the reduced rows is the fix that keeps the promise the tool's own
    `--check` help, its block header and `test_suite.py`'s check name all make:
    *a claim-only edit is invisible to it*. The alternative — dropping
    `not claimed_by` from `render()`'s sort — would make that true by deleting
    the readability the block states it wants ("a claimed one belongs to whoever
    holds the claim"), so the ORDER is canonicalised in the REDUCTION instead,
    which is where the machine is supposed to stop mattering.

    Rows are sorted WITHIN each contiguous run, not globally: the runs are the
    per-area tables, and a global sort would interleave two areas' rows and hide
    a document that moved between them.
    """
    out = []
    run = []
    for line in block.splitlines():
        if _is_row(line):
            cells = line.split('|')
            cells[2] = ' — '
            run.append('|'.join(cells))
            continue
        out.extend(sorted(run))
        run = []
        line = re.sub(r', \d+ claimed\b', ', — claimed', line)
        line = re.sub(r'^(\*\*)\d+ documents about the formal backend, '
                      r'\d+ of them CLAIMED[^.]*\.',
                      r'\1N documents about the formal backend.', line)
        line = re.sub(r'^(\*\*)\d+ documents, \d+ claimed\.',
                      r'\1N documents, — claimed.', line)
        out.append(line)
    out.extend(sorted(run))
    return '\n'.join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--json', action='store_true',
                    help='machine-readable: one record per document')
    ap.add_argument('--check', action='store_true',
                    help='fail when OPEN_WORK.md\'s generated block is stale, '
                         'IGNORING the claim column (a fact about the machine)')
    ap.add_argument('--strict', action='store_true',
                    help='with --check, compare the claim column too')
    ap.add_argument('--write', action='store_true',
                    help='rewrite OPEN_WORK.md\'s generated block in place')
    args = ap.parse_args()

    if args.json:
        print(json.dumps([{
            'doc': r[0], 'area': r[1], 'area_from': r[3],
            'runner_up': r[2], 'claimed_by': r[4],
            'title': r[5],
        } for r in rows()], indent=1, sort_keys=True))
        return 0

    block = render()
    if args.write:
        text = open_work_text()
        current = block_in(text)
        if current is None:
            print(f'error: {os.path.relpath(OPEN_WORK, ROOT)} has no '
                  f'generated block — the markers\n  {BEGIN}\n  {END}\n'
                  f'are missing, so there is nothing safe to replace.',
                  file=sys.stderr)
            return 2
        open(OPEN_WORK, 'w', encoding='utf-8').write(
            text.replace(current, block, 1))
        print(f'{os.path.relpath(OPEN_WORK, ROOT)}: generated block rewritten '
              f'({len(rows())} documents)')
        return 0

    if args.check:
        current = block_in(open_work_text())
        if current is None:
            print(f'FAIL  formal doc index: '
                  f'{os.path.relpath(OPEN_WORK, ROOT)} has no generated block '
                  f'(markers missing)')
            return 1
        want = block.strip() if args.strict else without_claims(block).strip()
        have = (current.strip() if args.strict
                else without_claims(current).strip())
        if have == want:
            n = len(rows())
            n_claimed = sum(1 for r in rows() if r[4])
            drift = ''
            if current.strip() != block.strip():
                drift = (f' — the CLAIM column has also moved '
                         f'({n_claimed} of {n} claimed now; the block says '
                         f'otherwise). Not a failure by design: that column is a '
                         f'fact about the machine. `--write` if you want it.')
            print(f'PASS  formal doc index: {n} documents, block current'
                  f'{drift}')
            return 0
        print(f'FAIL  formal doc index: the block in '
              f'{os.path.relpath(OPEN_WORK, ROOT)} is stale — a document was '
              f'added or deleted, or an area or a title moved. Run '
              f'`python3 tools/formal_doc_index.py --write`.')
        import difflib
        diff = list(difflib.unified_diff(have.splitlines(), want.splitlines(),
                                         'OPEN_WORK.md', 'generated',
                                         lineterm='', n=1))
        for line in diff[:40]:
            print('   ' + line)
        return 1

    print(block)
    return 0


if __name__ == '__main__':
    sys.exit(main())