#!/usr/bin/env python3
"""Generates ab.mk: one real GNU Make rule per (file, side) for the
aside/bside A/B dump-compare harness, so `make -j20 aside`/`make -j20
bside` get genuine per-file parallelism from Make's own job server
(not just an internal worker-pool argument some other script interprets).

Regenerated automatically by the main Makefile's `-include ab.mk` +
`ab.mk: ...` rule whenever tools/ab_filelist.py or this script changes, or
run directly: `python3 tools/gen_ab_makefile.py > ab.mk`.
"""
import os
import sys

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(TOOLS_DIR)
sys.path.insert(0, TOOLS_DIR)
import ab_filelist as fl  # noqa: E402


def _mk_escape(path: str) -> str:
    """Escape a path for safe use as a Make target/prereq (spaces only —
    none of these paths are expected to contain them, but cheap to guard)."""
    return path.replace(' ', '\\ ')


def main() -> None:
    entries = list(fl.discover())

    out = []
    out.append("# Auto-generated by tools/gen_ab_makefile.py — do not edit by hand.")
    out.append(f"# {len(entries)} files discovered by tools/ab_filelist.py.")
    out.append("")

    aside_targets = []
    bside_targets = []
    for key, src in entries:
        a_tgt = _mk_escape(f"aside/{key}.ci")
        b_tgt = _mk_escape(f"bside/{key}.ci")
        src_esc = _mk_escape(src)
        aside_targets.append(a_tgt)
        bside_targets.append(b_tgt)
        out.append(f"{a_tgt}: {src_esc}")
        out.append(f"\t@mkdir -p $(dir $@)")
        out.append(f"\t@python3 tools/ab_run_one.py --side a --key {key} --src '{src}'")
        out.append("")
        out.append(f"{b_tgt}: {src_esc} mojoc")
        out.append(f"\t@mkdir -p $(dir $@)")
        out.append(f"\t@python3 tools/ab_run_one.py --side b --key {key} --src '{src}'")
        out.append("")

    out.append("ASIDE_TARGETS := " + " \\\n  ".join(aside_targets))
    out.append("BSIDE_TARGETS := " + " \\\n  ".join(bside_targets))
    out.append("")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == '__main__':
    main()
