    hdr = ('"""gen_module implementation.\n\n'
           'Entire original GimpleGen.gen_module body, hoisted verbatim.\n'
           'Takes `self` (GimpleGen instance) and `stmts` (top-level AST '
           'statements);\nreturns the generated C source string.\n"""\n'
           'from __future__ import annotations\n'
           '\nimport os\nimport re\nimport sys\n'
           '\nfrom fire_compiler import (\n'
           '    IntLiteral, FloatLiteral, StringLiteral, TstringLiteral, BoolLiteral,\n'
           '    EllipsisLiteral, NoneLiteral,\n'
           '    IdentExpr, BinaryOp, CompareChain, UnaryOp, CallExpr, MemberExpr,\n'
           '    SubscriptExpr, SliceExpr, TernaryExpr, WalrusExpr, LambdaExpr,\n'
           '    ListExpr, DictExpr, SetExpr, TupleExpr, Comprehension,\n'
           '    VarDecl, AssignStmt, AugAssignStmt, MultiAssignStmt,\n'
           '    ReturnStmt, RaiseStmt,\n'
           '    BreakStmt, ContinueStmt, PassStmt, AssertStmt, ExprStmt,\n'
           '    ImportStmt, FromImportStmt,\n'
           '    IfStmt, WhileStmt, ForStmt,\n'
           '    FunctionDef, TryStmt, WithStmt,\n'
           '    ComptimeIfStmt, ComptimeForStmt, ComptimeVarStmt,\n'
           '    GlobalStmt, DelStmt, MatchStmt,\n'
           '    StructDef, TraitDef,\n'
           '    YieldExpr, YieldFromExpr, AwaitExpr,\n'
           '    py_tokenize, Parser,\n'
           ')\n'
           'from module_loader import load_module, get_symbol_type\n'
           'import ast_rewriter\n'
           'import mlir\n'
           'import regex_compile\n'
           'import gimple_ctypes\n'
           'import gimple_solvers\n'
           'import gimple_exprtypes\n'
           'from gimple_exprtypes import _walk_ast\n')
    old_hdr_never_used = ('"""gen_module implementation.\n\n'"